### ISSUE TITLE
Add support for Cloudant Search

### ISSUE THREAD

**Issue by alfinkel** [cloudant/python-cloudant#104]
We need to add support for creating Search Indexes in a DesignDocument as well as support for performing query searches through the `_search` endpoint targeting a Search Index.

This issue is dependent upon the completion of the bug fix #103.

**Comment by alfinkel** [comment]
ref:  https://docs.cloudant.com/search.html

**Comment by emlaver** [comment]
Item will be split into 3 issues:
1. Search index management
2. Search index query execution
3. Search index query result processing
