### ISSUE TITLE
Add default remote property to client and database

### ISSUE THREAD

**Issue by alfinkel** [cloudant/python-cloudant#116]
Add a property/attribute to the client account and database classes that dictates the remote refresh behavior for the represented object.  Currently the behavior is dictated by a `remote` argument on each  method that interacts with the remote database.

Propose:
- Add the private attribute `_remote` to the constructors of CouchDB (client/account) and CouchDatabase (database).
- Default the client/account `_remote` to `False`.
- Default the database `_remote' to take the value of the same property from the client/account.
- Add property getter/setter methods to both CouchDB and Couchdatabase.  For example:

``` python
@property
def remote(self):
    return self._remote

@remote.setter(self):
def  setter(self, val)
    self._remote = val
```

Add logic to the following methods to handle the new property

account methods affected:
- `keys`
- `__getitem__` - Currently there is no option here.  We should add one.
- `__delitem__`
- `__setitem__`
- `get`

database methods affected:
- `keys`
- `__iter__`
- `__getitem__` - Currently there is no option here.  We should add one.
- Currently no`get` method available.  It would be good to add one to keep things consistent with the account logic.

**Comment by emlaver** [comment]
Moving to backlog and low priority for now.  Changing this behavior will be a significant change to the API and should be handled in a major release with other breaking API changes.

**Comment by smithsz** [comment]
I think we should revisit this again. It's unclear which methods use locally cached data and which don't.
Setting a `remote` parameter on instantiation would be far simpler than dealing with it on every call imo.
Also, we should check which `dict` methods we aren't overriding to be sure that `remote=True`  is respected (i.e. the database `__contains__` only examines the local `dict`).

**Comment by ricellis** [comment]
We're no longer doing enhancements here.
