### ISSUE TITLE
Clean up _2to3.py

### ISSUE THREAD

**Issue by alfinkel** [cloudant/python-cloudant#128]
- Replace all `pylint: disable` comments with `#pylint: skip-file` at the top of the module.
- Fix docstring spelling from "semamtics" to "semantics".
- Remove unused code:
  - For example `RawConfigParser` can be moved to `tests/__init__.py`
  - Need to check if there is anything else to move/remove.

**Comment by ricellis** [comment]
No longer doing enhancements here.
