### ISSUE TITLE
Fix unidiomatic-typechecks in result module

### ISSUE THREAD

**Issue by alfinkel** [cloudant/python-cloudant#129]
- Replace the use of `type` checking in two "if statements of the `_validate` function with `isinstance` instead.
  - https://github.com/cloudant/python-cloudant/blob/master/src/cloudant/result.py#L86
  - https://github.com/cloudant/python-cloudant/blob/master/src/cloudant/result.py#L95
- Remove the `# pylint: disable=unidiomatic-typecheck` comment
  - https://github.com/cloudant/python-cloudant/blob/master/src/cloudant/result.py#L82
- Ensure all tests complete as expected.
- If necessary add tests to ensure that the isinstance checks work as expected.

**Comment by ricellis** [comment]
We're not doing enhancements here.
