### ISSUE TITLE
Add support for additional ddoc sub-objects

### ISSUE THREAD

**Issue by alfinkel** [cloudant/python-cloudant#137]
Currently we only provide a view management API through the DesignDocument, we need to investigate and add addition management API to the DesignDocument if necessary for things like List Functions, Show Functions, Filter Functions, indexes, etc...  See the [complete list](https://docs.cloudant.com/design_documents.html).

**Comment by alfinkel** [comment]
This issue may easily wind up being split into more granular GH issues.

**Comment by emlaver** [comment]
This issue will be split into the following:
- `rewrites` array with rules for URL rewriting
- Search index management (#159)
- Geospatial index management using the `st_indexes` property
- List functions under the `lists` array
  - In Database class, query _list i.e. `query_list(list_name, ddoc_id, mr_index, **kwargs)`
- Show functions using the `shows` array
  - In Database class, query _show: i.e. `query_show(show_name, ddoc_show_id, doc_id,  **kwargs)`
- Update handler custom functions
  - Query update handler with GET or POST request
- Filter functions to filter `changes` feed
- Update validators using the `validate_doc_update` property
- Retrieving information about a design document using `_info` endpoint
  - Obtains information about a given design document, including the index, index size and current status of the design document and associated index information.
- Retrieving information about a design document using `_search_info` endpoint
  - Obtains information about a search specified within a given design document.
