### ISSUE TITLE
create_database checks existence twice (3 RTTs)

### ISSUE THREAD

**Issue by ricellis** [cloudant/python-cloudant#142]
I was doing some testing and noticed that the `create_database` call makes two `GET` requests before the `PUT` to create a remote database.
This is what happens:
1. `client.create_database()` calls `database.exists()` which does a `GET`
2. If it didn't exist `client.create_database()` calls `database.create()`
3. `database.create()` calls `exists()` which does another `GET`
4. If the database does not exist then  `database.create()` finally does the `PUT`.

I think it could be beneficial to replace these three round trips with a single request to `PUT` given that if the database already exists a `412` is returned.
There is some complication in that currently `database.create()` would not throw for the `412` response case, but `client.create_database` optionally needs to throw.
- Cloudant (python-cloudant) version(s) that are affected by this issue.
  - 2.0.0b2 (probably others too)
- Python version 
  - any (tested on 2.7)
- A small code sample that demonstrates the issue.

``` python
client.create_database('abc')
```

**Comment by alfinkel** [comment]
These are now `HEAD` calls rather than `GET` fwiw but imo at least one of the `HEAD` calls should be removed.  See my comments on #279.
