### ISSUE TITLE
Add exception handling to InfiniteFeed implementation

### ISSUE THREAD

**Issue by alfinkel** [cloudant/python-cloudant#149]
Consider adding support for catching unexpected exceptions during iteration of an InfiniteFeed and handling (possibly restarting) if appropriate.

See https://github.com/cloudant/python-cloudant/pull/148/files#r60578978

**Comment by ricellis** [comment]
Not doing enhancements here. Currently our new [cloudant-python-sdk](https://github.com/IBM/cloudant-python-sdk/)(beta) doesn't have a changes follower, but we intend to add one that will have this restart functionality.
