### ISSUE TITLE
_common_util.py has a reference to os.uname() which isn't available on windows

### ISSUE THREAD

**Issue by rkhwaja** [cloudant/python-cloudant#163]
python-cloudant 2.0.0, python 3.5.1, windows 10 x64

"from cloudant import Account" demonstrates the issue

**Comment by ricellis** [comment]
Perhaps we could use `platform.system()` and `platform.machine()` instead.

**Comment by alfinkel** [comment]
Initially I was confused by the comment `"from cloudant import Account" demostrates the issue`.  We dont have an "Account" in this library so I think that would demonstrate a different issue...

Anyway, I think that if we change the os.uname() references to platform.uname() references [here](https://github.com/cloudant/python-cloudant/blob/master/src/cloudant/_common_util.py#L36-L37) then that would resolve the issue.

Change to:

```python
platform.uname()[0],
platform.uname()[4]
```

or @ricellis suggestion

```python
platform.system(),
platform.machine()
```
