### ISSUE TITLE
How to check if doc exists() 

### ISSUE THREAD

**Issue by thubregtsen** [cloudant/python-cloudant#166]
Hi,

I want to check if a document exists before I try to use it.

The requested details:
- Cloudant (python-cloudant) version(s) that are affected by this issue. <br>
Bluemix cloudant v2.0.0b2 database linked to the python app
- Python version  <br>
2.7
- A small code sample that demonstrates the issue.
```
   from cloudant.account import Cloudant
    import json
    # Connect to the database
    client = Cloudant(*hidden*)
    client.connect()
    # The database we work in
    db = client['myDatabase']
    # The document we work on
    doc = db['myDocument']
    print doc.exists()
```

If the document exists
    doc.exists() -> returns true
If the document does not exist
    doc = db['myDocument'] -> throws an error

How can I check before opening a file?

Question on stackOverflow (a bit differently formulated):
http://stackoverflow.com/questions/37029898/check-if-document-exists-using-cloudant-2-0-0b2-in-ibm-bluemix-and-python?noredirect=1#comment61652895_37029898

**Comment by alfinkel** [comment]
I posted the answer to StackOverflow.  See the [first answer](http://stackoverflow.com/questions/37029898/check-if-document-exists-using-cloudant-2-0-0b2-in-ibm-bluemix-and-python/37092115#37092115) on your SO question.
