### ISSUE TITLE
Utility method to format type checking error message

### ISSUE THREAD

**Issue by emlaver** [cloudant/python-cloudant#176]
An error message is returned when a query parameter is of the wrong type i.e. for limit :

> Argument stale is not an instance of expected type: `<type 'basestring'>`

This message could be a little confusing for the cases where we accept multiple types. For instance  `sort`:

> Argument sort is not an instance of expected type: `(<type 'basestring'>, <type 'list'>)`

One way to fix this: replace all the places these messages are generated with calls to a single utility method to format the message based on the number of types checked.

**Comment by alfinkel** [comment]
You certainly do love your utility methods.  But I would recommend that whatever solution you choose that it be considered within the context of the overall library exception handling process (which needs to be revamped/enhanced).  See #65.  I've made a small attempt at this with the [ResultException](https://github.com/cloudant/python-cloudant/blob/master/src/cloudant/error.py#L53-L78) shown in use [here](https://github.com/cloudant/python-cloudant/blob/master/src/cloudant/result.py#L221).

My point here is that whatever you choose to do should take the overall exception handling enhancement into account so as not to create something that may wind up being thrown away later or even worse, driving the exception handling solution.

**Comment by ricellis** [comment]
No longer doing enhancements here.
