### ISSUE TITLE
Documentation: connection pooling

### ISSUE THREAD

**Issue by snowch** [cloudant/python-cloudant#18]
One of the failings of the currently python library is that it doesn't describe how to use connection pooling.

This ticket is to track documentation that is quite important to developers around setting up and configuring connection pooling for this library.  For example:
1. information on instantiating the library so that it can be shared, e.g. using a singleton
2. calling out which methods are threadsafe and which aren't
3. describe how to configure connection pooling
4. describe how the library authenticates to Cloudant (using cookie or basic authentication)
5. describe if session expiry gets handled automatically by the library [1].  if not, what does the library consumer need to do to handle this?
6. how to use the library in common python application server environments [2] so that connection pooling can be configured at the app server level

---

[1] this assumes the library uses cookie authentication.  The [docs](https://docs.cloudant.com/authentication.html#cookie-authentication) state that the cookie can be used until it expires.
[2] e.g. django, flask, gunicorn

**Comment by snowch** [comment]
Is there a plan to get this stuff documented?  I have a flask app using vanilla python requests that I would like to migrate, but I don't really want to start digging into the source code of this library to find out how to use this library in a multi-threaded environment.

**Comment by rhyshort** [comment]
Yes, it's currently slated for our next release and is the second highest ticket in our backlog, (to view the backlog install zenhub and then click on boards in GH UI) so it is likely to get done for that release with the usual caveats eg something more important might spring up.

**Comment by snowch** [comment]
Awesome news, thanks @rhyshort.  If you would like a reviewer for the docs, I'm happy to help.

**Comment by jokereactive** [comment]
Hi! Is there some link or example to setup a connection pool for the latest cloudant-python api?

**Comment by emlaver** [comment]
@jokereactive You should be able to setup connection pool options using the HTTPAdapter from the `requests` library:
```
# Create client with 15 cached pool connections and a max pool size of 100
httpAdapter = HTTPAdapter(pool_connections=15, pool_maxsize=100)
client = Cloudant(USERNAME, PASSWORD, url='https://acct.cloudant.com'
                              connect=True,
                              adapter=httpAdapter)
```
Doc API for the HTTPAdapter: http://docs.python-requests.org/en/master/api/
Code for HTTPAdapter: https://github.com/kennethreitz/requests/blob/master/requests/adapters.py#L78

**Comment by jokereactive** [comment]
Thanks! Is there any documentation to fetch connections from this pool on parallel threads?  or do I have it as a static variable and it will handle the requests on it's own? Example -

```
httpAdapter = HTTPAdapter(pool_connections=15, pool_maxsize=100)
client = Cloudant(USERNAME, PASSWORD, url='https://acct.cloudant.com
                              connect=True,
                              adapter=httpAdapter)
# On parallel threads
# Some thing like this?
connection = client.getConnection()
# or 
# I use the client object as a static variable accessible to all threads
```

**Comment by emlaver** [comment]
@jokereactive After some testing with `Thread`, as long as the state of `client` does not change you should be able to use a static `client` that’s accessible to all threads.  In my test, I had a static `client` that was called by three separate threads.  
Here’s a gist of the code: https://gist.github.com/emlaver/0a5b8227088e6f6812f6d1061ea78d76
If you test this by executing the `run` method, the output will show that only one https connection is created and it's used for the create document request in each thread.

**Comment by jokereactive** [comment]
Thank you! This helps. :+1:
