### ISSUE TITLE
Query not returning all results

### ISSUE THREAD

**Issue by gsellers-ibm** [cloudant/python-cloudant#180]
Using v2.0.3 (and previously 2.0.0b2), Python 2.7.10. 

```
query_data = Query(db, selector={'type': 'x', sort=[{'created_at:number': 'desc'}])
query_res = query_data(limit=1000, skip=0)['docs']
```

When I do the above query, I'm expecting 300+ results, but Cloudant is only returning 200 results. I tried the same thing in the Cloudant UI and it seems that it's also initially returning 200 results, so this may be an inherent Cloudant bug and I've also raised a ticket with them.

I thought I might raise attention here as well in case someone else has encountered this.

**Comment by ricellis** [comment]
@gsellers-ibm: Thanks for reporting this. I have no problem returning more than 200 results from a database using version 2.0.3.
There is a syntax error in your example: missing the `}` on your selector. That would result in `SyntaxError: invalid syntax` so I'm guessing that was just a typo when raising the issue.

Is the index you created a `text` index? Text searches are limited to returning 200 results, you can get the next set by passing back the `bookmark` from the result.

**Comment by gsellers-ibm** [comment]
Oh sorry about the typo. And yeah, it was a text index, so that's probably why it was just returning 200. Thanks for the help.
