### ISSUE TITLE
Support read and write quorum parameters

### ISSUE THREAD

**Issue by JanekLehr** [cloudant/python-cloudant#184]
It would be nice if the client supported passing along the read and write quorum parameters that the Cloudant REST API supports, e.g `?r=3` and `?w=3`.
https://cloudant.com/for-developers/faq/data/

The [get_query_result()](https://github.com/cloudant/python-cloudant/blob/master/src/cloudant/database.py#L1076) method already supports the read quorum parameter, so there is precedence.
- **Cloudant (python-cloudant) version(s) that are affected by this issue.**  
  All
- **Python version**  
  All
- **A small code sample that demonstrates the issue.**
  
  ```
  doc = Document(db, document_id='my_doc')
  doc.fetch(r=3)  # The remote system will return to the requesting client with the document when 3 successful reads have been returned, and agree on versioning.
  ```

**Comment by ricellis** [comment]
I'm definitely not ruling out adding these parameters in future, but frequently people ask about using them when in nearly all circumstances the chosen defaults are sufficient.

If you'd like some more information about how these parameters can influence behaviour in an impaired system you might want to look at:

* [CouchDB 2.0's read and write behaviour in a cluster](http://www.dx13.co.uk/articles/2015/10/19/couchdb-20s-read-and-write-behaviour-in-a-cluster.html) 
* The section on _Impaired nodes_ in [CouchDB 2.0 - The awkward bits](http://events.linuxfoundation.org/sites/events/files/slides/ABDE_mike_wallace_couchdb_awkward_bits.pdf#53)

These highlight some of the difficulties faced when the quorum parameters are used to try and achieve some kind of stronger consistency. Ultimately the system is *eventually* consistent and applications need to tolerate that.

**Comment by JanekLehr** [comment]
Thank you for the material @ricellis. 
I found those API parameters when I was debugging an issue that stemmed from the application not tolerating eventually consistent data. Ultimately I am planning on using a consistent database but I thought those parameters should still be surfaced through the client.

**Comment by ricellis** [comment]
We're no longer doing enhancements here.
