### ISSUE TITLE
Release process

### ISSUE THREAD

**Issue by ksnavely** [cloudant/python-cloudant#21]
This lib should have a documented release strategy and process such that releases can be uploaded to pypi.

**Comment by alfinkel** [comment]
@ksnavely, the release process is documented at https://github.com/cloudant/cloudant-sync/blob/master/releasing-python-cloudant.md

**Comment by ewann** [comment]
@alfinkel: fwiw, those links are now 404

**Comment by alfinkel** [comment]
@ewann:  These are internal links.  I added them as reference for @ksnavely to review.
