### ISSUE TITLE
add asynchronous mode  

### ISSUE THREAD

**Issue by hasantuncer** [cloudant/python-cloudant#211]
The python-cloudant client (version 0.5.10) was providing async mode for database operations. However, in the 2.x.x version async mode is not supported. 

Last week, we experience long delays for put, get operations ranging from (72 seconds to 1 hour) using python client v 0.5.10 w/o asycn mode. Support team recommended us to move to version 2.x.x  To prevent, similar problems happening, we ask to have async mode. For details see Case #72985.
PS: We also look forward to contributing to this repo, once we finished moved to new client version.
Thanks

**Comment by ricellis** [comment]
Recent versions of the Requests library (which provides the HTTP for python-cloudant) do not support [non-blocking behaviour](http://docs.python-requests.org/en/latest/user/advanced/#blocking-or-non-blocking). So it looks like adding async support would require using one of the suggested projects that combine Requests with an async framework.

**Comment by Midnighter** [comment]
Is there any plan to implement this feature, for example with the excellent [requests-futures](https://github.com/ross/requests-futures)?

**Comment by emlaver** [comment]
Hi @Midnighter, we have no immediate plans to implement this enhancement.

**Comment by Midnighter** [comment]
Right, I just realized that this issue was put into the icebox :smiley: Thank you for letting me know.

**Comment by ricellis** [comment]
We won't add this feature here.

Our new [cloudant-python-sdk](https://github.com/IBM/cloudant-python-sdk/)(beta) doesn't yet have async either. However, it is built on the https://github.com/IBM/python-sdk-core and we hope to get asynchronous operation via that eventually.
