### ISSUE TITLE
Question on view and indexes

### ISSUE THREAD

**Issue by ayushidalmia** [cloudant/python-cloudant#214]
Hi,

I have a quick conceptual question.

Let us assume I have a database with three fields A,B and C. Now, I have added views using fields A and B. 

Now, I can create an index using the following manner:

```
index1  = my_database.create_query_index(fields=['a'],index_name="index_a")
index2 = my_database.create_query_index(fields=['b'],index_name="index_b")
index3 = my_database.create_query_index(fields=['a','b'],index_name="index_a_b")
```
Now I want to query using a selector from both fields a and b.

```
selector1 = {'a': {'$lt': 30}, 'b':{'$eq':5}}
docs1 = my_database.get_query_result(selector1,use_index = index_a)

selector2 ={'a': {'$lt': 30}, 'b':{'$eq':5}}
docs2 = my_database.get_query_result(selector2,use_index = index_a_b)
```

What does it mean to create an index using multiple fields (whose views are added)?
Will the second get_query_result return only one index even though we index it on two fields?
Which get_query_result will be faster and why?

**Comment by ricellis** [comment]
This question relates more to the Cloudant query service than specifically to the python-cloudant library. I recommend contacting support (either via email or raising a ticket on the dashboard).
