### ISSUE TITLE
test_get_search_result_with_both_q_and_query failure

### ISSUE THREAD

**Issue by ricellis** [cloudant/python-cloudant#222]
The test `tests.unit.database_tests.CloudantDatabaseTests.test_get_search_result_with_both_q_and_query` failed with this message:

```
Error Message
"A si[15 chars]rameter is required. Found: {'query': 'julia*', 'q': 'julia*'}" != "A si[15 chars]rameter is required. Found: {'q': 'julia*', 'query': 'julia*'}"
- A single query/q parameter is required. Found: {'query': 'julia*', 'q': 'julia*'}
?                                                   ----
+ A single query/q parameter is required. Found: {'q': 'julia*', 'query': 'julia*'}
```

The problem is that the test asserts a static message against a generated message wrt the query parameters, so the ordering is not guaranteed. We should either just assert the beginning of the message or make sure the parameters are compared or issued in the same order.
- Cloudant (python-cloudant) version(s) that are affected by this issue.
  - master
- Python version 
  - 3.5.2
- A small code sample that demonstrates the issue.
  - `tests.unit.database_tests.CloudantDatabaseTests.test_get_search_result_with_both_q_and_query`

**Comment by rhyshort** [comment]
This was fixed as part of 5e33426f75c83051192367c552041d100ecc1756
