### ISSUE TITLE
Context Manager as a Decorator

### ISSUE THREAD

**Issue by jcounts** [cloudant/python-cloudant#224]
Had a fun thought about adding a decorator that would be an alternate use for connection to a Cloudant/CouchDB account.

Example usage:

```
@cloudant('some_user', 'some_password')
def do_things_with_cloudant(client):
    client.create_database(database='mydb')
    #...
```

The first argument passed to the function would be the Cloudant/CouchDB account object (or may be better to go with something a bit more obvious like a kwarg specific say `client=client` in the above case). The idea here being that `connect` would be called upon entering the function and `disconnect` would be called on exit. I haven't yet looked into the technical details of implementing this but wanted to make a note of it as an interesting addition and something I'd like to look into. The idea stems from how `mock.patch` can be used as a decorator to start and stop the patching of code.

**Comment by evansde77** [comment]
I actually did this a while back while I was playing with some examples for class decorators: 

https://gist.github.com/evansde77/f9c0f1784431bd544c35c98786c6c3c9

**Comment by ricellis** [comment]
We're not doing enhancements here.
