### ISSUE TITLE
Plans for Python 3 support

### ISSUE THREAD

**Issue by FvD** [cloudant/python-cloudant#23]
Could you specify in the readme if you have any plans for Python 3 support in the (near) future?. 

Perhaps it would make sense to start a list with items to fix for Py3 support such as the use of [basestring](https://github.com/oxplot/fysom/issues/1)  and [type.NoneType](https://bugs.python.org/issue19438).

**Comment by alfinkel** [comment]
Support for Python 3 is on our radar, for sure.  In all likelihood we will look at that once the library is in a stable release (2.0.0).

**Comment by alfinkel** [comment]
We need to test the library in a Python 3 environment and react accordingly.  Any bugs found or changes that need to be made will be handled as separate GH issues.

Additionally as part of this effort we should also add to the Travis CI testing in multiple environments including Python 3.
