### ISSUE TITLE
Clean up append_response_error_content function

### ISSUE THREAD

**Issue by alfinkel** [cloudant/python-cloudant#240]
The` _common_util.append_response_error_content` function currently has an unused `**kwargs` argument as part of the function signature and a `#pylint: disable=unused-argument` comment to force pylint to ignore this.  In this case, pylint is correct in flagging `**kwargs` as unused and it should be removed along with the pylint "disable" comment.  Also the function could stand to be cleaned up and rewritten.  Suggest this:

```python
def append_response_error_content(response):
    resp_dict = response.json()
    if response.status_code >= 400 and resp_dict is not None:
        reason = resp_dict.get('reason', '')
        error = resp_dict.get('error', '')
        response.reason = '{0} {1}'.format(error, reason)
    return response
```

**Comment by emlaver** [comment]
This issue was solved in #260
