### ISSUE TITLE
Improve pylint reporting

### ISSUE THREAD

**Issue by emlaver** [cloudant/python-cloudant#244]
python-cloudant 2.0.0
Python 2.7.11 ad 3.5.1

@alfinkel wrote: it might be worthwhile to add some logic to https://github.com/cloudant/python-cloudant/blob/master/tests/unit/lint_test.py#L29 to simply print out the report if `not passed` and then change the .travis.yml to run tests as `nosetests -w tests/unit -s`.  This way if pylint complains as part of travis we’ll have the actual complaint in the build logs.

**Comment by ricellis** [comment]
I think we should break `pylint` out of the unit test entirely and just run it independently using the status code (see below) to fail the CI/build. This will also ensure the `pylint` report is in the output logs.

`pylint --long-help`
```
  Output status code:
    Pylint should leave with following status code:
    * 0 if everything went fine
    * 1 if a fatal message was issued
    * 2 if an error message was issued
    * 4 if a warning message was issued
    * 8 if a refactor message was issued
    * 16 if a convention message was issued
    * 32 on usage error
    status 1 to 16 will be bit-ORed so you can know which different
    categories has been issued by analysing pylint output status code
```
I think this means anything that isn't a 10/10 would be non-zero.

I think we could go as far as changing the report format to something Jenkins can use as well if we wanted to.

**Comment by rhyshort** [comment]
Having something jenkins could read would be a massive improvement, and more inline with the java libs and findbugs.

**Comment by emlaver** [comment]
@ricellis @rhyshort What about printing out part of report when running `nosetests` so we don't have to separate `pylint` from the unit tests.  Something like: 
```
nosetests -w tests/unit -s
........................................S..................SSSSSSSSSSSSSSSSSSSSSSSSS...............SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS...............................................SSSSSSSSSSSSSSSS..............................S............S....SS...........................................................................SSSSSSSSSSSSSSSSSSS...SSSSSSSSSS...S..F................................SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS.......................................................................................................
======================================================================
FAIL: Apply Pylint to Python-Cloudant Client Library
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/estebanmlaver/python-cloudant/tests/unit/lint_test.py", line 55, in test_pylint_cloudant
    self.assertTrue(passed, fail_msg)
AssertionError: Pylint check failed.  Code is required to be rated at 10.00/10.  Please review the warnings or errors found:
 
************* Module cloudant.client
W: 23, 0: Unused import os (unused-import)
C: 23, 0: standard import "import os" comes before "import requests" (wrong-import-order)


Report
======
1636 statements analysed.

Global evaluation
-----------------
Your code has been rated at 9.99/10 (previous run: 9.99/10, +0.00)

Run pylint cloudant for more details.
-------------------- >> begin captured logging << --------------------
requests.packages.urllib3.connectionpool: INFO: Starting new HTTP connection (1): 127.0.0.1
requests.packages.urllib3.connectionpool: DEBUG: "DELETE /_config/admins/user-071986cd-0583-49ab-997f-e86d14b5db5e HTTP/1.1" 200 87
--------------------- >> end captured logging << ---------------------

----------------------------------------------------------------------
Ran 533 tests in 26.279s

FAILED (SKIP=148, failures=1)
```

**Comment by ricellis** [comment]
I prefer to separate the `pylint` static analysis isn't really a unit test. The only downside I can think of separating it is that in a development workspace you would need to run the commands for both `nosetests` and `pylint`.

**Comment by emlaver** [comment]
@ricellis I've got a branch up now and it's running pylint separately from unit tests.  Here you can see that pylint is run first then nose tests in the output from this travis job: https://travis-ci.org/cloudant/python-cloudant/jobs/189249993

**Comment by ricellis** [comment]
@emlaver great - one thing I noticed:
>The command "pylint ./src/cloudant && nosetests -w ./tests/unit" exited with 0.

That approach will mean not running the tests if the pylint fails. That can be useful if we don't want to waste test execution time when changes are going to have to be made anyway, but the alternative viewpoint is that once you have queued for CI you should get the whole report so you can fix everything before re-submitting.

In the `.travis.yml` you can have multiple script steps e.g.
```yaml
script: 
  - pylint ./src/cloudant 
  - nosetests -w ./tests/unit
```
If you did that both pylint and the tests would always run and we could get the result for each since [travis will run all steps and accumulate the build result](https://docs.travis-ci.com/user/customizing-the-build/#Customizing-the-Build-Step).

**Comment by emlaver** [comment]
@ricellis Can we close this ticket or should we keep it open for possibly improving the pylint report format in Jenkins?

**Comment by ricellis** [comment]
@emlaver Thanks, I think close it. We'll see how it goes with the just the build failure and if we find that we need the report tracking in Jenkins we'll open another item.
