### ISSUE TITLE
Implement method to create Cloudant client from VCAP services environment variable

### ISSUE THREAD

**Issue by smithsz** [cloudant/python-cloudant#254]
Add an additional method to parse a `VCAP_SERVICES` environment variable allowing easy binding of a service instance to a Cloud Foundry application.

Example `VCAP_SERVICES` variable is JSON:
```json
{
    "cloudantNoSQLDB": [
        {
            "credentials": {
                "username": "example",
                "password": "xxxxxxx",
                "host": "example.cloudant.com",
                "port": 443,
                "url": "https://example:xxxxxxx@example.cloudant.com"
            },
            "syslog_drain_url": null,
            "label": "cloudantNoSQLDB",
            "provider": null,
            "plan": "Lite",
            "name": "Cloudant NoSQL DB"
        }
    ]
}
```

**Comment by mikerhodes** [comment]
FWIW I think that the method should take in the json.parsed VCAP_SERVICES variable as an argument rather than pulling it from the environment itself. This allows the application to retrieve it from different sources and avoids the library dictating deployment policy to the consuming application.

**Comment by mikerhodes** [comment]
Also, the `service_name` variable needs renaming. The `service_name` is the top-level `cloudantNoSQLDB`. I think we mean `instance_name`, that is `Cloudant NoSQL DB` in the above.
