### ISSUE TITLE
Documentation - provide a list of code bases showing exemplary use of python-cloudant

### ISSUE THREAD

**Issue by snowch** [cloudant/python-cloudant#276]
It would be great if we could provide a list of open source code bases that show python-cloudant being used as part of a bigger application such as flask and django.

I have put together a demo application with one sub-goal being to show python-cloudant used with flask:

 - https://github.com/snowch/movie-recommender-demo

The majority of the Cloudant code is in the following two files:

 - https://github.com/snowch/movie-recommender-demo/blob/master/web_app/app/dao.py 
 - https://github.com/snowch/movie-recommender-demo/blob/master/web_app/app/cloudant_db.py

The above app probably needs work before it can serve as an example.  I'm far from being an expert on python-cloudant!

**Comment by emlaver** [comment]
I've added three python examples (2 using flask app) to [examples in open source projects](https://github.com/cloudant/python-cloudant#examples-in-open-source-projects).  Closing this issue.
