### ISSUE TITLE
how to retrieve attachments from document

### ISSUE THREAD

**Issue by webe3** [cloudant/python-cloudant#278]
I have documents with attachments.  I can see the attachments but how do you actually retrieve the attachment?

(Pdb) first_doc
{'_id': 'bc3cc646c9d184320a269813cfd43e91', '_rev': '2-d29f36cef8ba04a9f33e667f78024fb3', '_attachments': {'20160618_CV_Emrah_Akyol.pdf': {'stub': True, 'content_type': 'application/json', 'revpos': 2, 'length': 107206, 'digest': 'md5-ct/niRm6esd30BUNpw4Glg=='}}, 'dateUploaded': 1483977251272, 'name': '20160618_CV_Emrah_Akyol', 'uploaderRole': 'admin', 'uploaderID': 'son@xxx.com', 'groups': ['Uiuc - Post-doc']}
(Pdb) first_doc['_attachments']
{'20160618_CV_Emrah_Akyol.pdf': {'stub': True, 'content_type': 'application/json', 'revpos': 2, 'length': 107206, 'digest': 'md5-ct/niRm6esd30BUNpw4Glg=='}}
(Pdb) first_doc['_attachments']['20160618_CV_Emrah_Akyol.pdf']
{'stub': True, 'content_type': 'application/json', 'revpos': 2, 'length': 107206, 'digest': 'md5-ct/niRm6esd30BUNpw4Glg=='}

**Comment by alfinkel** [comment]
Have you tried?: http://python-cloudant.readthedocs.io/en/latest/document.html#cloudant.document.Document.get_attachment

**Comment by webe3** [comment]
I just tried it and it works perfectly.  Thank you.
In order for me to get the attachment name, I did the following:
attach_name = next(iter(first_doc['_attachments']))
another way would be
for attach_name in first_doc['_attachments']:

Is there a better way?

**Comment by alfinkel** [comment]
If I understand your question correctly, it seems like you're asking more of a Python question as opposed to a python-cloudant library question.  A python-cloudant Document object is a sub-class of `dict` so when you retrieve your Cloudant document content as a python-cloudant Document object you can access that content as you would from a `dict`.

So to answer your question, you can retrieve the attachment name(s) for your attachment(s) by using any valid Python `dict`-like retrieval function.
