### ISSUE TITLE
Add support for _local document management

### ISSUE THREAD

**Issue by alfinkel** [cloudant/python-cloudant#284]
Add support for the manipulation of `_local` documents.

**Comment by alfinkel** [comment]
I began work on this but soon came to the realization that `_local` document support needs to be handled differently between CouchDB and Cloudant.  I closed the PR #290 but it can be reopened later when we have some additional time to work out all of the differences and come up with a clean homogeneous solution for the handling of `_local` documents.

**Comment by ricellis** [comment]
Won't fix here.

Our new [cloudant-python-sdk](https://github.com/IBM/cloudant-python-sdk/)(beta) can do [local docs](https://cloud.ibm.com/apidocs/cloudant?code=python#putlocaldocument).
