### ISSUE TITLE
Cloudant exception should throw 412 when database already exists

### ISSUE THREAD

**Issue by emlaver** [cloudant/python-cloudant#287]
Currently we are throwing a `CloudantClientException` with 409 status code when it should be 412: https://github.com/cloudant/python-cloudant/blob/master/src/cloudant/client.py#L229. 
This can be confirmed by trying to create an existing database and checking the status code for `resp`: https://github.com/cloudant/python-cloudant/blob/master/src/cloudant/database.py#L343.

**Comment by porthunt** [comment]
A 409 status code seems to be ok for `CloudantClientException`:

`409: 'Database {0} already exists.'`.

I think the biggest issue is related to the CloudantDatabaseException. We might need a 412 status code for an already existing database.
