### ISSUE TITLE
all_docs call with keys=[] returns all results

### ISSUE THREAD

**Issue by Sampanna01S** [cloudant/python-cloudant#289]
- Cloudant (python-cloudant) version(s) that are affected by this issue.
   2.3.0
- Python version
N/A
- It looks like using the `keys` parameter in view requests does not work as expected when `keys` is the empty list.  The expectation would be that no rows of data is returned but the current behavior is that all rows of data are returned.

**Comment by alfinkel** [comment]
I believe that all that needs to be done here is to fix this line of code: https://github.com/cloudant/python-cloudant/blob/master/src/cloudant/_common_util.py#L245 with `if keys is not None:` and add a test to validate the fix.

**Comment by smithsz** [comment]
Merged fix.
