### ISSUE TITLE
Database.create_document throw_on_exists bug

### ISSUE THREAD

**Issue by alfinkel** [cloudant/python-cloudant#291]
[Line 163](https://github.com/cloudant/python-cloudant/blob/master/src/cloudant/database.py#L163) will still throw an HTTPError if the `throw_on_exists` flag is set to `False` in [Database.create_dcoument](
https://github.com/cloudant/python-cloudant/blob/master/src/cloudant/database.py#L154-L165).

**Comment by smithsz** [comment]
Merged fix.
