### ISSUE TITLE
Custom query parameters for list function

### ISSUE THREAD

**Issue by iblis17** [cloudant/python-cloudant#294]
Hi, I have an elaborated `list` function which accepts a custom query parameter.

e.g.
```
curl 'http://localhost:5984/market/_design/ddoc/_list/mylist/myview?startkey=\["foo"\]&myargs=42'
```

Is it possible query it with `get_list_function_result` ? I tried but got following error.

```python
/home/iblis/venv/py36/lib/python3.6/site-packages/cloudant/_common_util.py in py_to_couch_validate(key, val)
    176     """
    177     if key not in RESULT_ARG_TYPES:
--> 178         raise CloudantArgumentError(116, key)
    179     # pylint: disable=unidiomatic-typecheck
    180     # Validate argument values and ensure that a boolean is not passed in

CloudantArgumentError: Invalid argument myargs

In [36]: r = db.get_list_function_result('_design/ddoc', 'mylist', 'myview', limit=1, myargs=42)
```

**Comment by alfinkel** [comment]
Only the arguments defined by the [RESULT_ARG_TYPES](https://github.com/cloudant/python-cloudant/blob/master/src/cloudant/_common_util.py#L51-L67) can be used with `get_list_function_result`.  If you want to use anything beyond those arguments you can use the database object's `r_session` to execute your request directly and handle the raw content returned as needed.  See [here](http://python-cloudant.readthedocs.io/en/latest/getting_started.html#endpoint-access).  The example shows the use of the `client.r_session` but the `r_session` exists on the database, document, and design document objects as well.  It is basically a straight shot to the request session where you can perform any HTTP request directly.

Obviously other options also exist such as overriding the behavior of `get_list_function_result` to be less restrictive.

Hopefully that helps.

**Comment by iblis17** [comment]
Thanks @alfinkel ! `r_session` works fine.
