### ISSUE TITLE
Document context manager throws an exception with doc_id is None

### ISSUE THREAD

**Issue by tknorris** [cloudant/python-cloudant#298]
Currently the Document context manager attempts to fetch the document in __enter__ which throws an exception if doc_id is None. At the moment you have to write code like the following to do a combined update/create:
```
    if doc_id is None:
        doc = Document(db)
        doc.update(value)
        try:
            doc.save()
        except:
            print 'Save Failed: %s' % (len(json.dumps(value)))
    else:
        with Document(db, doc_id) as doc:
            try: doc.update(value)
            except:
                print 'Update Failed: %s' % (len(json.dumps(value)))
```

If the fetch() was only done when doc_id is not None then the context manager could be used for new and existing documents.

**Comment by ricellis** [comment]
We're not doing enhancements here.
