### ISSUE TITLE
pylint failure on Python3

### ISSUE THREAD

**Issue by smithsz** [cloudant/python-cloudant#301]
```
$ pylint ./src/cloudant
************* Module cloudant._common_util
E:286,28: Undefined variable 'unicode' (undefined-variable)
...
```

**Comment by emlaver** [comment]
I had another failure because I didn't have urllib3 installed in my python environment.  We need to add `urllib3` in [requirements.txt](https://github.com/cloudant/python-cloudant/blob/master/requirements.txt).
