### ISSUE TITLE
Improve session objects

### ISSUE THREAD

**Issue by smithsz** [cloudant/python-cloudant#310]
Currently we have 3 session types:
- ClientSession (inherits from requests.Session)
- CookieSession (inherits from ClientSession)
- IAMSession (inherits from ClientSession)

There's a lot of duplicated logic between CookieSession/IAMSession. These should inherit from a base class AuthSession(ClientSession).

`client.py` is forever calling `if self.admin_party:` before performing session functions. This logic should move to the Session object. Perhaps implement a new AdminPartySession where login/logout methods are noop functions.

**Comment by ricellis** [comment]
Won't fix.
