### ISSUE TITLE
Using cloudant_bluemix function throws an exception

### ISSUE THREAD

**Issue by rofrano** [cloudant/python-cloudant#311]
The current `cloudant_bluemix` function doesn't appear to work. It throws an exception because it uses incorrect syntax to create the Cloudant class. 

**Using:**

- cloudant==2.5.0
- Python 2.7.12
- Python 3.6.2

**Steps to reproduce**

The following code illustrates the problem given the `VCAP_SERVICES` environment variable has been set by Bluemix (or manually):
```
import os
from cloudant import cloudant_bluemix
with cloudant_bluemix(os.getenv('VCAP_SERVICES')) as client: 
    print(client.all_dbs())
```

**Expected results**  

A list of databases from your CloudantNoSQL service in Bluemix. e.g.:
```
[u'images', u'items', u'orders', u'status']
```

**Observed results in Python 2.7.12**

When executing the code in Python 2.7.12 the following exception occurs:
```
Traceback (most recent call last):
  File "test.py", line 3, in <module>
    with cloudant_bluemix(os.getenv('VCAP_SERVICES')) as client: 
  File "/usr/local/Cellar/python/2.7.13_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/Users/rofrano/bx-test/venv/lib/python2.7/site-packages/cloudant/__init__.py", line 128, in cloudant_bluemix
    **kwargs
TypeError: __init__() takes exactly 3 arguments (1 given)
```
**Observed results in Python 3.6.2**

When executing the code in Python 3.6.2 the following exception occurs:
```
Traceback (most recent call last):
  File "test.py", line 3, in <module>
    with cloudant_bluemix(os.getenv('VCAP_SERVICES')) as client: 
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/Users/rofrano/github/bx-test/venv/lib/python3.6/site-packages/cloudant/__init__.py", line 128, in cloudant_bluemix
    **kwargs
TypeError: __init__() missing 2 required positional arguments: 'cloudant_user' and 'auth_token'
```
**Offending code on line 128**

Line 128 of `./cloudant/__init__.py` passes all parameters as **kwargs when the first two parameters should be passed as args:
```
    cloudant_session = Cloudant(
        username=service.username,
        password=service.password,
        url=service.url,
        **kwargs
    )
```

**Correct code**

This version of line 128 in `./cloudant/__init__.py` fixes the problem:
```
    cloudant_session = Cloudant(
        service.username,
        service.password,
        **dict(kwargs, url=service.url)
    )
```
It seems to be working fine for me with this change. I can fix it and send a pull request if you want (up to you).

**Comment by smithsz** [comment]
Hey @rofrano, thanks for bringing this to our attention. I'll get a fix out tomorrow and add some additional testing around the bluemix client constructor too. Apologies for the inconvenience this has caused.

**Comment by rofrano** [comment]
@smithsz no worries. Glad I could help in some small way.
