### ISSUE TITLE
Add get_query_result convenience method to CouchDatabase

### ISSUE THREAD

**Issue by vvasuki** [cloudant/python-cloudant#316]
I had the same question as https://github.com/cloudant/python-cloudant/issues/234 , and I think found what I was looking for. But, it would have been much better if get_query_result convenience method were in CouchDatabase, where I sought in vain.

**Comment by ricellis** [comment]
Yes, this is a hangover from when query was specific to Cloudant before it merged into CouchDB 2.0. I'll leave this open as we may eventually we may get around to refactoring for the Couch 2 APIs. As you've seen using the `CloudantDatabase` works for many CouchDB 2 functions.

**Comment by ricellis** [comment]
We're not doing any enhancements here. In our new [cloudant-python-sdk](https://github.com/IBM/cloudant-python-sdk/)(beta) there is currently no segregation between Couch/Cloudant functionality - if it is necessary to introduce that kind of API split then query functionality will definitely also be available to the Couch models.
