### ISSUE TITLE
Cloudant.bluemix does not work on IBM Bluemix Dedicated service

### ISSUE THREAD

**Issue by peterpk** [cloudant/python-cloudant#330]
Please include the following information in your ticket.

- Cloudant (python-cloudant) version(s) that are affected by this issue.  *2.6.0*
- Python version  *3.6.2*
- A small code sample that demonstrates the issue.  *See below*

IBM Bluemix Dedicated service uses "cloudantNoSQLDB Dedicated" as the name of the service, rather than "cloudantNoSQLDB" used by Public Bluemix.  Unfortunately, the CloudFoundryService class hardcodes the value:   `cloudant_services = services.get('cloudantNoSQLDB', [])`

Any chance we could make that value a parameter?

**Comment by ricellis** [comment]
Thanks for reporting this, we'll look at getting something added.

In the meantime you should be able to workaround by specifying the username, password and account in the `Cloudant(user, pass, account=...)` format instead.
