### ISSUE TITLE
Unable to create replications when specifying src/tgt databases as string

### ISSUE THREAD

**Issue by smithsz** [cloudant/python-cloudant#337]
_Repro:_
```
client = Cloudant(
    cloudant_user='user123',
    auth_token='xxxxxxxxx',
    url='https://user123.cloudant.com',
    connect=True
)
replication_doc = Replicator(client).create_replication(
    source='src_db',
    target='tgt_db'
)
```
_Error:_
```
Traceback (most recent call last):
  File "bugtest.py", line 18, in <module>
    continuous=False
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/cloudant/replicator.py", line 96, in create_replication
    if not target_db.admin_party:
AttributeError: 'NoneType' object has no attribute 'admin_party'
```

I think a null check on `target_db` is required [here](https://github.com/cloudant/python-cloudant/blob/2.7.0/src/cloudant/replicator.py#L96) before calling `.admin_party`.

**Comment by emlaver** [comment]
@smithsz Wouldn't this issue be more of an enhancement since `source_db` and `target_db` can currently either be a `CouchDatabase` or a  `CloudantDatabase` instance?

**Comment by smithsz** [comment]
The docs say `source` & `target` can be either `str` or `dict` representing the source/target database. I couldn't get it to work with strings so I think it's a bug.

**Comment by emlaver** [comment]
@smithsz Ok, my mistake.  I was looking at the `source_db` and `target_db` docs.
