### ISSUE TITLE
HTTPError: 404 Client Error: Object Not Found not_found Database does not exist

### ISSUE THREAD

**Issue by trojek** [cloudant/python-cloudant#338]
I use cloudant 2.7.0 version and python 3.5.

I execute the following code:

```
client = Cloudant(user, pass, url=url)
client.connect()
user_db = client.create_database(_uuid)
credentials = client.generate_api_key()
user_db.share_database(credentials['key'], roles=['_reader', '_replicator', '_writer'])
```

once for several executions of the code I get an error: requests.exceptions.HTTPError: 404 Client Error: Object Not Found not_found Database does not exist. for url: https://name.cloudant.com/8f1b3ae4-2be3-4789-becb-a0721dd8f173/_security

**Comment by tomblench** [comment]
@trojek how often is this is occurring? My understanding of "once for several executions" is that this is only happening occasionally or intermittently, is this correct?

It's possible that there is a race condition between `client.create_database` and `user_db.share_database ` because it may take some time to create the database but the underlying HTTP call is asynchronous so it returns immediately.

The only way to ensure that the database has been created before the call to `user_db.share_database` is to check the existence of the database in a loop before.

**Comment by trojek** [comment]
Hi @tomblench,
It is hard to say how often it occurs. I just made several tests and sometimes it occurs 1/10 times, but sometimes 7/10 times.
It definitely looks that I want to add privileges to the database which don't exist. 
I will make a loop which checks if the database exists as you suggested. Thank for the answer.
Tomek

**Comment by trojek** [comment]
I added to my above code:

`while True:
            time.sleep(.500)
            if user_db.exists():
                break`
and currently, sometimes it takes more than 30 seconds in order to create an account. Is it the normal situation?

**Comment by emlaver** [comment]
Hi @trojek, did you mean it may take 30 seconds or more to create the database named `_uuid`?
I've done 10+ test runs with your code above and it finished every time between 5-10 seconds, but we are also using different ISPs and our Cloudant accounts are probably on clusters in different regions.
I would recommend that you contact our support team via support@cloudant.com with your account name for further investigation.

**Comment by trojek** [comment]
Hi @emlaver. Sometimes it takes about 8 seconds (to execute all above code, not only create database with `_uuid`. But sometimes it take over 30 second. It occurs in series. I have quite good quality of Internet connection.

**Comment by emlaver** [comment]
@trojek this may be a side effect of eventual consistency.  The request to create the database may not have been on the same node as subsequent requests, even the `exists()` check may or may not reach the same nodes.  
I still recommend that you contact our support team if you’re concerned about the performance of your cluster.

**Comment by trojek** [comment]
I contacted with Cloudant support. I will let you (@emlaver) know when I solve the problem.

**Comment by trojek** [comment]
The problem is with gunicorn, not Cloudant itself. I do numerous of test with the same code "alone" and inside the pythons frameworks which work on gunicorn.
