### ISSUE TITLE
Honoring PAC and/or PAC auto-discovery

### ISSUE THREAD

**Issue by BillBridge** [cloudant/python-cloudant#350]
Does python-cloudant support PAC files and/or PAC auto discovery? And if so, how can I configure this?
I am using python-cloudant version 2.6.0 with python 2.7.14

**Comment by ricellis** [comment]
No, it does not.

The only proxy support in python-cloudant at the moment is that provided by the underlying [requests library](http://docs.python-requests.org/en/master/). We don't expose a way to customize the arguments on every request, but you should be able to configure a proxy address to be used via the [`HTTPS_PROXY` environment variable](http://docs.python-requests.org/en/master/user/advanced/#proxies), but this isn't something we've tested AFAIK.

**Comment by tomblench** [comment]
Closing old ticket.
