### ISSUE TITLE
Offline usage

### ISSUE THREAD

**Issue by somelinguist** [cloudant/python-cloudant#351]
Is it possible to use python-cloudant when a remote connection is not available without installing CouchDB or a compatible DB locally to run against?  Sort of like Cloudant Sync, but for Python?
———

Please include the following information in your ticket.

- Cloudant (python-cloudant) version(s) that are affected by this issue.  2.7.0
- Python version 3.6.4
- A small code sample that demonstrates the issue. N/A

**Comment by ricellis** [comment]
No, there is no database built-in to provide an offline store.

**Comment by somelinguist** [comment]
Thanks. That's what I thought.
