### ISSUE TITLE
Improve documentation of raised exceptions

### ISSUE THREAD

**Issue by abaruni** [cloudant/python-cloudant#353]
There is a lack of documentation around the exceptions that can be raised. For example looking at the documentation for the documents API http://python-cloudant.readthedocs.io/en/latest/document.html#cloudant.document.Document.save there is no mention or any exceptions being raised. However, i see the call `put_resp.raise_for_status()` in documents.py: https://github.com/cloudant/python-cloudant/blob/master/src/cloudant/document.py#L189

After digging around i see that python-requests is used under the covers and this `raise_for_status()` is on requests.Response.

so, it would be valuable to document that any methods that call `raise_for_status()` may raise an `HTTPError`.

It is difficult to provide effective error handling when using this client without knowing if/which exceptions may be raised

**Comment by ricellis** [comment]
Closing, we're not making these kind of improvements here any longer, but this is definitely a valid point which we've tried to address in our new SDK.

For our new [cloudant-python-sdk](https://github.com/IBM/cloudant-python-sdk/)(beta) we have [specific error handling documentation and examples](https://cloud.ibm.com/apidocs/cloudant?code=python#error-handling).
