### ISSUE TITLE
Improve examples in readthedoc's getting started

### ISSUE THREAD

**Issue by emlaver** [cloudant/python-cloudant#355]
WIP Documentation work items for [getting started](http://python-cloudant.readthedocs.io/en/latest/getting_started.html):
- `view` example(s)
  - Show view -> result flow
  - `result` attribute by default has reduce=True (#356)
  - Example of using `custom_result` context manager
- `result` example(s)
  - Complex key range
- Handling exception example(s) #353 

Other possible items:
- Show example(s) in README?

**Comment by ricellis** [comment]
As per issue #417 we could add examples for using `get_query_result` and updating documents e.g. https://github.com/cloudant/python-cloudant/issues/417#issuecomment-452077468

**Comment by emlaver** [comment]
Closed by accident in #423.
#423 merged which added `get_query_result` example.

**Comment by ricellis** [comment]
Closing, we're not making these kind of improvements here.

Our new [cloudant-python-sdk](https://github.com/IBM/cloudant-python-sdk/)(beta) has more extensive documentation and [comprehensive examples](https://cloud.ibm.com/apidocs/cloudant?code=python#introduction) for every supported operation.
