### ISSUE TITLE
Updating document

### ISSUE THREAD

**Issue by abshkd** [cloudant/python-cloudant#36]
I have tried your documents and gone through the source code. For some reason a request is never made to save() the document.

In your sample code:
 there is no mention of _rev but I added it from your API reference. 
You import Document but never use it. 

Whatever is happening it isnt working. Having wasted a few days on the Cloudant I am ready to move on simply because I don't want to commit more time here. Had I known earlier about this like when I started with Elasticsearch I might have just use plain ol' requests library to construct my queries.

Can someone atleast take a look at prove me wrong and foolish

**Comment by mikerhodes** [comment]
@abshkd 

Sorry to hear about the problems; certainly sounds like we've got something wrong here. I appreciate your persevering a few days on the problem.

First thing to double check: which version of the library are you using -- is it the 2.0 version from this repository or the 0.x version? The two versions are essentially different libraries, so I'd like to check you're not trying to use the docs from here (which are for 2.0) with the 0.x library. I admit this is confusing, and we're working to retire the old version to avoid this problem ASAP.

Secondly, could you post the code which failed, so I can reproduce your issue? It sounds like you're trying to do a simple document write, which should be working -- the 2.x version of the library is currently an alpha release, however, and we're currently filling out our test coverage to catch obvious bugs of which this might be one.

For what it's worth, I can update a document using the following virtualenv setup and code:

```
~/s/python-cloudant> mkdir issue-36
~/s/python-cloudant> cd issue-36/

~/s/p/issue-36> virtualenv .
New python executable in ./bin/python
Installing setuptools, pip...done.
~/s/p/issue-36> . ./bin/activate.fish
(issue-36)~/s/p/issue-36> pip install --pre cloudant
Downloading/unpacking cloudant
  Downloading cloudant-2.0.0a4-py2-none-any.whl
Downloading/unpacking requests>=2.7.0,<3.0.0 (from cloudant)
  Downloading requests-2.8.1-py2.py3-none-any.whl (497kB): 497kB downloaded
Installing collected packages: cloudant, requests
Successfully installed cloudant requests
Cleaning up...

(issue-36)~/s/p/issue-36> python main.py 
Created document.
Name is now: Julia
Updated document.
Name is now: Jules
(issue-36)~/s/p/issue-36>
```

And `main.py`. I pointed out the line I understand is failing for you, can you confirm whether I'm correct?

```python
USERNAME = "mikerhodescloudant"
PASSWORD = "password"
ACCOUNT_NAME = "mikerhodescloudant"

from cloudant.account import Cloudant
client = Cloudant(USERNAME, PASSWORD, account=ACCOUNT_NAME)

# Connect to the account and establish a session cookie
client.connect()
session = client.session()

# Create a database
my_database = client.create_database('my_database')

# Create a document containing `data`
data = {
    '_id': 'julia30', # Setting _id is optional
    'name': 'Julia',
    'age': 30
    }
my_document = my_database.create_document(data)
if my_document.exists():
    print 'Created document.'

# To update a document, first retrieve it, then update it, then save it
# Need to GET the doc if you don't have it already. (We already do here)
# my_document = my_database['julia30']
print "Name is now:", my_document['name']
my_document['name'] = 'Jules'
my_document['age'] = 6
my_document.save()  # <-- my understanding is that this is failing for you?

# Delete the document
# Need to GET the doc if you don't have it already. (We already do here)
# my_document = my_database['julia30']
print "Name is now:", my_document['name']
my_document.delete()

# Clean up and disconnect
client.delete_database('my_database')
client.disconnect()
```

**Comment by alfinkel** [comment]
@abshkd, regarding your comment about importing the Document but never using it in our example, I found the reference in the "Getting Started" section of the docs where that happens.  Apologies for that, we will have that removed in the upcoming release.  But that would not cause the issue that you are having right now.  Like @mikerhodes mentioned, if you could provide us with the code that is failing for you so that we could reproduce the problem, we could work towards getting you back on track using this library.

**Comment by abshkd** [comment]
Sorry I missed your email. Thanks for looking into it.

Here is the code I am using. The id does get set correctly.

i am using 2.0 Pre-alpha with the docs for the same.

Its a simple enough code but I notice a slight difference. You dont use _id
but name which is a user defined field. I am setting ids myself and they
are unique strings.



m_doc = db.get(q.get()) #q is a list of _id
m_doc['start'] = my_func('block_address')#my_func returns an int
value, start is a new field.
m_doc.save()

I could be completely wrong but I have tried different ways of doing this
and get the same result.

Thanks again.

**Comment by alfinkel** [comment]
@abshkd, the code does look simple enough and should work given the right conditions which I am detailing below.  But can you clarify your comment here: `m_doc = db.get(q.get()) #q is a list of _id`?  Is *q* really a python `list`?  If so, how do you perform a `get()` call on it?  Also, are you getting any errors?  If so can you send them as well?

I am going to assume that `q.get()` returns a valid _id for a document and that you are NOT getting any error when running this code.  Based on these two assumptions, the only way for your code snippet to work is if the db object already has the Document stored in its locally cached dictionary.  This can happen either if you had previously executed the `db.create_document(...)` method call for that document or you had retrieved the document from the remote database and into the db locally cached dictionary with `db['...']`. The example below illustrates this.  It includes your code snippet in its entirety.  I have validated that the example does in fact work.  Can you take a look at it and see if any of this helps you along?  If not, please send the full code block from "client connect" through "disconnect" and I think we can definitely resolve the problem.

Also fwiw, `db.get('docid')` will only get the locally cached Document if it is there while `db['docid']` will attempt to get the document from the remote database if it cannot find it in the local "db" dictionary.

```python
class Q(object):
    def __init__(self, id):
        self._my_id = id
        
    def get(self):
        return self._my_id

q = Q('my-generated-id-001')

def my_func(x):
    return 123

from cloudant import Cloudant

client = Cloudant(USERNAME, PASSWORD, account=ACCOUNT)
client.connect()
db = client['my_database']
# displays the locally cached "db" dictionary - should be empty
print 'local cache before doc create: {0}'.format(db) 
# Creates the document remotely and stores it locally in the "db" dictionary
m_doc = db.create_document({'_id': q.get()})
print 'm_doc after create: {0}'.format(m_doc)
# displays the locally cached "db" dictionary - should contain m_doc document
print 'local cache after doc create: {0}'.format(db)
del db[q.get()] # Clear the locally cached "db" dictionary
# displays the locally cached "db" dictionary - should be empty now
print 'local cache before doc retrieval (after clearing cache): {0}'.format(db)
# Retrieve the document and store it in the locally cached "db" dictionary
db[q.get()] 
# displays the locally cached "db" dictionary - should contain m_doc document
print 'local cache after doc retrieval: {0}'.format(db) 

del m_doc
# Your code block
m_doc = db.get(q.get()) #q is a list of _id
m_doc['start'] = my_func('block_address')#my_func returns an int
m_doc.save()

print 'm_doc after update: {0}'.format(m_doc)
client.disconnect()
```

Example output:

```
local cache before doc create: {}
m_doc after create: {'_rev': u'1-967a00dff5e02add41819138abb3284d', '_id': u'my-generated-id-001'}
local cache after doc create: {u'my-generated-id-001': {'_rev': u'1-967a00dff5e02add41819138abb3284d', '_id': u'my-generated-id-001'}}
local cache before doc retrieval (after clearing cache): {}
local cache after doc retrieval: {'my-generated-id-001': {u'_rev': u'1-967a00dff5e02add41819138abb3284d', u'_id': u'my-generated-id-001'}}
m_doc after update: {'start': 123, u'_rev': u'2-4c902ca8dfc3c4e99b6c53605ba3d0a7', u'_id': u'my-generated-id-001'}
```

**Comment by abshkd** [comment]
Hi Alfinkel, Thank you very much. Let me understand your notes completely and try this again. 
On your question, q is a python queue, it will pop an Id after doc retrieval. this is my code

    def test_database():
     from cloudant.account import Cloudant
     client = Cloudant('user', 'password', account="account")
     client.connect()
     return client["mydb"]

    def get_db_ids(db):
     store = []
     results = Result(db.all_docs)
     for result in results:
         store.append(result['id'])
    return store


Based on what you said, I believe I should try ['id'] or return the entire ResultSet in my function above.

**Comment by abshkd** [comment]
Hi,
So I tested whether the document actually is selected in my function with a print after the q.get() and even used [] list method. The document does indeed get assigned to m_doc before I add my field and do a save. However still no luck saving. 

I am using '_id' parameter like this 
    m_doc = db[my_doc['_id']]

I found the problem in my logging so I wasnt showing errors as I should. I have however seen this error before

...
[snipped]
 m_doc.save()
  File "/usr/local/lib/python2.7/dist-packages/cloudant/document.py", line 148, in save
    self.create()
  File "/usr/local/lib/python2.7/dist-packages/cloudant/document.py", line 110, in create
    resp.raise_for_status()
  File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 837, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 409 Client Error: Conflict for url: https://my_username.cloudant.com/mydb


The save() obviously is trying to create a new document. That shouldn't happen right? Specially since m_doc['_rev'] is correctly displaying the revision numbers just before I do a save(). I am using the pip install --pre Cloudnat package.

**Comment by abshkd** [comment]
managed to set document_id property using Document() object directly, still no luck.

**Comment by alfinkel** [comment]
@abshkd, based on your traceback, it looks like you are using an older version of the library.  The latest version is 2.0.0a4.  Can you do a `pip freeze` in your environment and see which version you are on.  If necessary upgrade to the most recent.  This may not solve your issue but at least we could confirm that we are working from the same starting point.  You are right about the 409 conflict.  The reason for it is the empty `_document_id`.  There is one known bug in the database iterator (to be fixed  soon) that could cause this condition but based on your code snippets it does not appear that you are using the iterator.  So I don't think that is the issue here.  If you could please attach your full code block with all manipulation of your database object and Document object I could then recreate the problem on my end.  As I see it we either have a coding logic problem or there is something special with your document ids that we need to account for in our code.  To that end can you give me one document id value that causes this to fail and also confirm that if you create a database with a set of documents that have the document ids of 'my-doc-id-001' through 'my-doc-id-100' that you still experience the same updating problems?  If we can confirm that it is not an _id encoding/formatting issue we can then just focus on the logic.  I appreciate you sticking with this for so long and rest assured we will get to the bottom of this problem and have you back on track.

**Comment by alfinkel** [comment]
Closed due to lack of response
