### ISSUE TITLE
How proceed further when document does not exist in database  ?

### ISSUE THREAD

**Issue by ZaheerUdDeen** [cloudant/python-cloudant#366]
In the given code below I want to access the specific document which exists in some databases.

what the problem here is when the program does not find a document in the databases it gives an error.
but I want to proceed and find the document in all databases.
![image](https://user-images.githubusercontent.com/11150958/37879099-4dbee576-308c-11e8-8ba8-b3834af0b13b.png)
here is the error.
![image](https://user-images.githubusercontent.com/11150958/37879138-07a47de8-308d-11e8-8759-7dc5bebbe609.png)

**Comment by emlaver** [comment]
@ZaheerUdDeen you'll need to use the `Document` object and the `fetch` method to load the document from a Cloudant account.

For example:
```
client = Cloudant('username', 'password', account='username')
client.connect()
database_names = client.all_dbs()
for db_name in database_names:
    db = client[db_name]
    doc = Document(db, 'document-id')
    # Retrieve the content of the current document from the remote database
    doc.fetch()
    print(doc)
```
