### ISSUE TITLE
How to work with same library from python Notebook in watson studio ?

### ISSUE THREAD

**Issue by ZaheerUdDeen** [cloudant/python-cloudant#367]

**Comment by emlaver** [comment]
Hi @ZaheerUdDeen, you'll need to install the library in your notebook.  There are [instructions here](https://datascience.ibm.com/docs/content/analyze-data/importing-libraries.html) under `To install a Python library` that show you need to run `!pip install --user cloudant` in a cell.  
Once the package is successfully installed, you can run your python code.
For example:
```
from cloudant.client import Cloudant
from cloudant.document import Document

client = Cloudant('username', 'password', account='username')
client.connect()
database_names = client.all_dbs()

for db_name in database_names:
    db = client[db_name]
    doc = Document(db, 'doc')
    doc.fetch()
    # do something with doc
```
