### ISSUE TITLE
sort changed sort_field for get_search_result()

### ISSUE THREAD

**Issue by gurusrin** [cloudant/python-cloudant#370]
In the new version of the Cloudant, the `sort`  parameter has been changed to `sort_field` for searching using design documents. Therefore, this needs to be updated in `_common_util.py` file accordingly, so that function `get_search_result()` is able to return the results properly.

Current function call:
`
results = get_search_result(designDoc, indexName, sort = "myfield<number>")
`

Modification required as per new change:

`
results = get_search_result(designDoc, indexName, sort_field = "myfield<number>")
`

**Comment by emlaver** [comment]
@gurusrin I didn't find any reference about the change from `sort` to `sort_field` in the [IBM Cloud documentation](https://console.bluemix.net/docs/services/Cloudant/api/search.html#search).  Could you please share the link where you found this info?

**Comment by emlaver** [comment]
@gurusrin Could you please contact our support team via support@cloudant.com with your account name so we can further investigate? Thanks.

**Comment by rnewson** [comment]
I don't think this was changed. more likely you specified an invalid value to 'sort' and got an error. When you switched to 'sort_field', you didn't get an error because we don't examine unknown parameters, but you wouldn't get the right sort order either.

**Comment by gurusrin** [comment]
Upon working with the Cloudant Support, I found that the mistake was at my end. I had been assuming the sort field to be integer but actually it appeared to be a string field. After making the appropriate changes, the results are coming fine.
