### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'info'

### ISSUE THREAD

**Issue by Megidd** [cloudant/python-cloudant#374]
Information regarding my issue:

#### Cloudant (python-cloudant) version(s) that are affected by this issue

```
$ pip show cloudant
Name: cloudant
Version: 2.8.1
Summary: Cloudant / CouchDB Client Library
Home-page: https://github.com/cloudant/python-cloudant
Author: IBM
Author-email: alfinkel@us.ibm.com
License: UNKNOWN
Location: /home/uconn/.local/lib/python2.7/site-packages
Requires: requests
Required-by: 
```

#### Python version 

```
$ python2.7
Python 2.7.12 (default, Dec  4 2017, 14:50:18) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> 
```

#### A small code sample that demonstrates the issue, saved inside a file name `script.py`. This code is written according to [documentation](http://python-cloudant.readthedocs.io/en/latest/getting_started.html#getting-started):

```
# Use CouchDB to create a CouchDB client
from cloudant.client import CouchDB
client = CouchDB('admin', '****', url='https://192.168.1.106:6984')

# Perform client tasks...
session = client.session()
print('Username: {0}'.format(session['userCtx']['name']))
print('Databases: {0}'.format(client.all_dbs()))

db = client['sample']

# Disconnect from the server
client.disconnect()
```

#### When running the above sample code, I receive this error:

```
$ python2.7 script.py 
Traceback (most recent call last):
  File "script.py", line 6, in <module>
    session = client.session()
  File "/home/uconn/.local/lib/python2.7/site-packages/cloudant/client.py", line 165, in session
    return self.r_session.info()
AttributeError: 'NoneType' object has no attribute 'info'
```

**Comment by emlaver** [comment]
@Megidd You'll need to start up an authentication session for the client with [`client.connect()`](http://python-cloudant.readthedocs.io/en/latest/client.html#cloudant.client.CouchDB.connect) e.g.
```
...
client = CouchDB(...)
client.connect()
session = ...
...
```
Another option is to add `connect=True` parameter when you create `client`:
```
client = CouchDB('admin', '****', url='https://192.168.1.106:6984', connect=True)
```

**Comment by Ringenberg** [comment]
Please do not forget to update the documentation with this clarification as trying to run the example code with a CouchDB triggers the error.

**Comment by emlaver** [comment]
I added `connect=True` parameter in 9bd7718.
