### ISSUE TITLE
Document save

### ISSUE THREAD

**Issue by chosun41** [cloudant/python-cloudant#375]
Python - 3.6.4

Not sure if this is an actual bug. But it seems one needs to save the local cache multiple times instead of one time before saving information to a document. Original code only had doc.save() at end.

New code:

        end =  datetime.datetime.utcnow()
        doc = db[kwargs['inbt']['_id']]
        doc['api_result'] = kwargs['results']
        doc['end_time_utc'] =  time.mktime(end.timetuple())
        duration = (end-kwargs['inbt']['start']).total_seconds()
        doc['duration'] = round((duration)/60,2)
        doc.save()
        if 'et_results' in kwargs.keys():
            doc['et_results'] = kwargs['et_results']
            doc.save()
        if 'forecast' in kwargs.keys():
            doc['forecast'] = kwargs['forecast']
            doc.save()
        if 'encoded' in kwargs.keys():
            doc.put_attachment(attachment = "encode.bin",data = kwargs['encoded'], content_type = 'application/octet-stream')
        doc.save()
        return doc

**Comment by chosun41** [comment]
I originally only had the one doc.save() after the doc.put_attachment. In that case, only the attachment was saved.

**Comment by emlaver** [comment]
@chosun41 have you changed your environment since using the original code? Updated python version or other Python packages?

**Comment by smithsz** [comment]
Stale ticket. Please reopen if you require further assistance.
