### ISSUE TITLE
Add dbcopy to a view?

### ISSUE THREAD

**Issue by jroyal** [cloudant/python-cloudant#38]
Is this possible in python-cloudant? In cloudant-python you would just pass the whole view dictionary which could have dbcopy as a field. 

For example in cloudant-python you could do something like this. 

```python

view = {
    "page_id_tester": {
        "map": "function (doc) {\n if(doc.alarm_id) {\nemit(doc.alarm_id, "
               "doc); }}",
        "reduce": "function (keys, values, rereduce) { var latest = ''; var "
                  "ts = 0; var i = 0; for(i = 0; i < values.length; i++){ "
                  "if(values[i]['timestamp'] > ts){ ts = values[i]["
                  "'timestamp']; latest = values[i];}}return latest;}",
        "dbcopy": "page-view-db"
    }
}

response = design_doc.put(params={
        "_id": "_design/%s" % name,
        "views": view
    })
```

But if i'm reading the documentation correctly, python-cloudant restricts view creation in a design document by allowing you to pass in map and reduce strings. So is it not currently possible, or am I just missing something(totally possible)?

**Comment by alfinkel** [comment]
@jroyal, the easiest way to do what you want to do in this library is:

```python
view_def = {
    "page_id_tester": {
        "map": "function (doc) {\n if(doc.alarm_id) {\nemit(doc.alarm_id, "
               "doc); }}",
        "reduce": "function (keys, values, rereduce) { var latest = ''; var "
                  "ts = 0; var i = 0; for(i = 0; i < values.length; i++){ "
                  "if(values[i]['timestamp'] > ts){ ts = values[i]["
                  "'timestamp']; latest = values[i];}}return latest;}",
        "dbcopy": "page-view-db"
    }
}

# assuming a connection to "database"
with DesignDocument(database, '_design/ddoc001') as ddoc:
    ddoc['views'].update(view_def)
```

This will either create or update the design document `_design/ddoc001` and either create or update the `page_id_tester` view on the server depending on whether they already exist there.

Now, I'll say that you are definitely hitting upon something that needs to be enhanced, which is the way in which we handle views.  The DesignDocument/View API that we are currently providing does appear to be limiting the content of the view.  This should/will be fixed.  But know that you can always circumvent any of these restrictions in the meantime by treating any of these objects (View, DesignDocument, Document, etc...) as a dictionary which they all do extend.

I've labeled this issue as an enhancement so we can work towards making the API a bit more inclusive and friendly.  Let me know if this works for you.

**Comment by alfinkel** [comment]
One other thing of note here is that as a symptom of the current View API, the DesignDocument.fetch() routine ignores any content other than map and reduce functions from the retrieved view.  So even if you have a design document with a `dbcopy` entry on the server, the fetch will incorrectly return only the map and reduce functions.  This is clearly a bug and will be resolved as part of the API enhancement effort for this issue.

**Comment by jroyal** [comment]
@alfinkel Thanks! I think that's what I'm looking for. I'll try it out and let you know if I run into any issues.
