### ISSUE TITLE
409 Client Error: Conflict conflict Document update conflict when creating document

### ISSUE THREAD

**Issue by edwardstudy** [cloudant/python-cloudant#398]
Please [read these guidelines](http://ibm.biz/cdt-issue-guide) before opening an issue.

## Bug Description
```
                with Document(whitelist_db, id) as document:
                    current_time = dt.datetime.now().isoformat()
                    if document.exists():
                        print 'Updating whitelist item "{0}"'.format(id)
                        document['type'] = 'id'
                        document['expired_date'] = whitelist_item['expiry']
                        document['contact'] = whitelist_item['contact']
                        document['updated_time'] = current_time
                        document.save()
                    else:
                        print 'Creating whitelist item "{0}"'.format(id)
                        new_item = {
                            '_id': id,
                            'type': 'id',
                            'contact': whitelist_item['contact'],
                            'expired_date': whitelist_item['expiry'],
                            'created_time': current_time,
                            'updated_time': current_time,
                        }
                        document=whitelist_db.create_document(new_item)
```
Run code above return error:

  File "/usr/local/lib/python2.7/site-packages/cloudant/document.py", line 346, in __exit__
    self.save()
  File "/usr/local/lib/python2.7/site-packages/cloudant/document.py", line 189, in save
    put_resp.raise_for_status()
  File "/usr/local/lib/python2.7/site-packages/requests/models.py", line 939, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 409 Client Error: Conflict conflict Document update conflict. for url: https://cloudant_url

### 2. What you expected to happen
Updated or created new document
### 3. What actually happened
Return 409 error if trying to create new document
## Environment details

Cloudant > 2.9.0
python > 2.7.11

**Comment by tomblench** [comment]
If you are using the `with` construct you don't need to explicitly save. You can do something like:

```python
    def create_or_update(self):
        id = "my_test_doc"
        with Document(self.db, id) as document:
            if document.exists():
                print 'Updating whitelist item "{0}"'.format(id)
                document['status'] = "updated"
            else:
                print 'Creating whitelist item "{0}"'.format(id)
                document['status'] = "created"
```
When I call `create_or_update` twice, I can see a `1-` rev with `status=created` and a `2-` rev with `status=updated`.

**Comment by emlaver** [comment]
Closing as stale, please reopen if you require further assistance.
