### ISSUE TITLE
Cannot get db_info from a document with unicode in the id

### ISSUE THREAD

**Issue by jcounts** [cloudant/python-cloudant#401]
Please [read these guidelines](http://ibm.biz/cdt-issue-guide) before opening an issue.

### 1. Steps to reproduce and the simplest code sample possible to demonstrate the issue

The following (where `user` and `password` are assumed to be correctly defined):
```
with cloudant(
    user,
    password,
    account='someuseraccount'
) as client:
    db = client['somedatabase']
    ddoc = db[u'\u05de\u05d2\u05d9\u05e2(\u05d4)']
    pprint.pprint(ddoc.info())
```

### 2. What you expected to happen
Results of `ddoc.info()` should be returned.

### 3. What actually happened
`KeyError: u'\u05de'` is raised.

## Environment details
- Version(s) that are affected by this issue.
    > 2.9.0
- Python version
    > 2.7.15

**Comment by smithsz** [comment]
Can you please try passing the Python string version instead? i.e.
```py
ddoc = db[u'_design/\u05de\u05d2\u05d9\u05e2(\u05d4)'.encode('utf-8')]
```
Let me know how you get on.

**Comment by jcounts** [comment]
Using `encode` works.

We are planning on moving to python3 soon, I recall reading that there are some issues converting `encode`/`decode` from 2 to 3. Do you have any advice on a way to try and future proof this?

**Comment by smithsz** [comment]
I'm afraid not. You'll need to adapt your code when moving to Py3 since calling encode on a str will give you the new byte type, not a str.

Please reopen if you have any further questions.
