### ISSUE TITLE
Cannot set filter parameters in changes() call

### ISSUE THREAD

**Issue by mythsmith** [cloudant/python-cloudant#402]
The Feed._validate method makes it impossible to pass arbitrary query parameters to a _changes filter design document when calling CouchDatabase.changes().
https://github.com/cloudant/python-cloudant/blob/4435d84f24dd3563e4abd2929e2953eeba0d5b89/src/cloudant/feed.py#L114
If the key is not in arg_types, it should assume it is a custom parameter directed at the filter and hope. Maybe just check if it is an int, float, or str, as these are the only supported types for the query.

I suppose the same holds for Cloudant._db_updates().

**Comment by rajinib** [comment]
Thanks for bringing this to our attention.  We will add this to our backlog and prioritize as needed.
