### ISSUE TITLE
Make query()['docs'] contain cloudant.document.Document instead of dict

### ISSUE THREAD

**Issue by rominf** [cloudant/python-cloudant#417]
Please [read these guidelines](http://ibm.biz/cdt-issue-guide) before opening an issue.

### 1. Steps to reproduce and the simplest code sample possible to demonstrate the issue

```python
from cloudant.client import CouchDB
from cloudant.query import Query

couchdb = CouchDB('admin', 'password', url='http://127.0.0.1:5984', connect=True)
couchdb.create_database('todos')
todos = couchdb['todos']
todos.create_document({'what': 'Show the query + update usecase', 'done': False})
query = Query(todos, selector={'what': 'Show the query + update usecase'})
doc = query()['docs'][0]
type(doc)  # dict
doc = todos[doc['_id']]
type(doc) # cloudant.document.Document
doc['done'] = True
doc.save()
```

### 2. What you expected to happen
As you see, if I want to update some queried document, first I have to extract it again as `cloudant.document.Document` using:
```python
database[doc['_id']]
```
It's not convenient. Why documents are not extracted as `cloudant.document.Document` when I call query?

### 3. What actually happened
Document are extracted as `dict`.

## Environment details

- Version(s) that are affected by this issue.
    > 2.10.2 (but I found that the code is the same in master too)
- Python version
    > 3.7.1 (irrelevant)

**Comment by emlaver** [comment]
Hi @rominf, please use the recommended `get_query_result(...)` function in the `Database` module.  There are some [documented examples](http://python-cloudant.readthedocs.io/en/latest/database.html#cloudant.database.CloudantDatabase.get_query_result) of iterating docs returned from it.

Something like this should work:
```python
todos = couchdb['todos']
selector = {'what': 'Show the query + update usecase'}
result = todos.get_query_result(selector)
for doc in result:
   doc['done'] = True
   doc.save()
```

**Comment by rominf** [comment]
@emlaver, thank you. That's what I needed. Why doesn't this example written in "Getting started"? I suggest to add it there.

**Comment by rominf** [comment]
It's very strange, but now it doesn't work, as I expect:
```python
from cloudant.client import CouchDB
couchdb = CouchDB('admin', 'password', url='http://127.0.0.1:5984', connect=True)
menu_plan_types = couchdb['menu_plan_types']
selector = {'name': 'business'}
for menu_plan_type in menu_plan_types.get_query_result(selector):
    print(type(menu_plan_type))
# <class 'dict'>
```
When I try to save, I get an exception of course. Why it's not working stabily?

**Comment by emlaver** [comment]
@rominf What's the exception you are getting?

**Comment by rominf** [comment]
@emlaver, I'm getting:
```
AttributeError: 'dict' object has no attribute 'save'
```
Because it's a `dict`, but not `Document`.

Is there a way to force this function always return collection of `Document`s?

**Comment by emlaver** [comment]
@rominf since the query results will be of type `dict` you'll need to create a `Document` object (passing in the Database object and doc id), update the doc, then save:
```
for doc in result:
   # Copy doc
   updated_doc = Document(todos, doc['_id'])
   updated_doc.update(doc)
   # Update doc
   updated_doc['done'] = True
   # Save
   updated_doc.save()
```

**Comment by rominf** [comment]
Ok, thank you for an answer, @emlaver. Can you please include this into documentation (as it's not obvious)?
