### ISSUE TITLE
get_query_result wrong type for selector

### ISSUE THREAD

**Issue by thesimj** [cloudant/python-cloudant#424]
## Bug Description
Wrong parameter type description in docstring for function `get_query_result()`

### 1. Steps to reproduce and the simplest code sample possible to demonstrate the issue
Install library and use type hint in Pycharm 2018

### 2. What you expected to happen
Proper param description, like
```python
def get_query_result(self, selector, fields=None, raw_result=False,
                         **kwargs):
"""
......
:param dict selector: Dictionary object describing criteria used to
            select documents.
....
""""
```
### 3. What actually happened
```python
def get_query_result(self, selector, fields=None, raw_result=False,
                         **kwargs):
"""
......
:param str selector: Dictionary object describing criteria used to
            select documents.
....
""""
```
## Environment details
Latest

**Comment by emlaver** [comment]
@thesimj Thanks for spotting this.  I'll open up a PR with the change.

**Comment by thesimj** [comment]
@emlaver your welcome, I found several more issue with argument type. 

Add more correction in pull request https://github.com/cloudant/python-cloudant/pull/426
