### ISSUE TITLE
Investigate Feed implementation

### ISSUE THREAD

**Issue by alfinkel** [cloudant/python-cloudant#45]
- We need to investigate how the Feed class is implemented.  Specifically, how a continuous feed works.  It appears that the endpoint parameters (for a continuous feed) are not being used to manage how a `_changes` or a `_db_updates` call is handled.
- Got feedback from user of 0.5.9 cloudant-python lib.
  - He uses the changes feed and saw that the changes feed in this library doesn't function the same as before.  We need to ensure that we are providing an optimal feed solution.

See: https://github.com/cloudant-labs/cloudant-python/issues/31 and https://github.com/cloudant-labs/cloudant-python/pull/33

**Comment by alfinkel** [comment]
A request from @willholley on Slack:

It would be very useful to be able to fetch _changes in batches rather than an infinite iterator in python-cloudant

I’m batching changes from one database and inserting them into another for the insert, I need to batch updates together but with an iterator, I can’t know when I’ve reached the end

**Comment by alfinkel** [comment]
Rename changes module to feed.

- changes.py -> feed.py

**Comment by evansde77** [comment]
FWIW the iterator has a non-continuous mode which should allow fetching in batches using since etc:
https://github.com/cloudant/python-cloudant/blob/master/src/cloudant/changes.py#L51
Looks like it is hard coded into params though:
https://github.com/cloudant/python-cloudant/blob/master/src/cloudant/changes.py#L51

**Comment by alfinkel** [comment]
Yeah, that hardcoding into the params appears to be the root cause of the problem.  However, if I override it by setting the `_params` to `{'feed': 'normal'}` when setting `continuous=False` I do get the iterator to complete but there is still some issue with the processing of the feed content.  I don't think it is a major issue but with that said I'll still have to dig a little deeper into it before coming up with the full resolution.  Thanks @evansde77 for pointing that out.

**Comment by evansde77** [comment]
Looks like I did a shitty job testing it :)

**Comment by alfinkel** [comment]
You and me both.

**Comment by alfinkel** [comment]
The continuous and non-continuous feeds return different response stream content.  A continuous feed returns change results whereas a non-continuous feed returns change results in a "result" array along with a "last_seq" number.  The result array and the last_seq number make up a dictionary object.  Because of this difference, we need to handle the response slightly differently for non-continuous feeds.  Currently the logic only handles the continuous feed cleanly.

Ref: https://docs.cloudant.com/database.html#get-changes

Scrolling down this reference will show the two different response type examples.  In addition to fixing the hardcoding of the feed, we also need to add logic to handle a non-continuous feed type response.

**Comment by alfinkel** [comment]
Plan of action is as follows:

- Update logic to handle non-continuous feed to retrieve the entire response (not as a stream) from the server while continuous feed processing will remain as is (streamed).
- Add logic to handle iterating over the non-continuous feed result list.  See bullet above.
- Change `self._last_seq` to `self.last_seq` and make it a property with a getter and setter so that the last sequence number will be available to the developer.
- Add heartbeat support as in [0.5.9 version](https://github.com/kxepal/cloudant-python/blob/4ef520a1c0be3e07fd4f1954a48f989aff6dea20/cloudant/database.py#L100).
- Allow for the chunk_size to be specified as a kwarg, if desired.
- Ensure that Feed works with both `_changes` and `_db_updates`.
