### ISSUE TITLE
connection to couchdb server via ipv6 address does not work

### ISSUE THREAD

**Issue by ManfredEnning** [cloudant/python-cloudant#461]
Please [read these guidelines](http://ibm.biz/cdt-issue-guide) before opening an issue.

## Bug Description
cloudant.couchdb does not work with ipv6 server addresses like 
http://[fd78:3214:6290:d772::1:51]:5984

### 1. Steps to reproduce and the simplest code sample possible to demonstrate the issue

        with cloudant.couchdb('admin', '@@@', url='http://[fd78:3214:6290:d772::1:51]:5984') as db:
            print(db)

### 2. What you expected to happen
the couchdb server should be connected

### 3. What actually happened
requests.exceptions.InvalidURL: Failed to parse: http://fd78:3214:6290:d772::1:51:5984/_session

## Environment details

Python 3.6

Remark: 

the erroneous code can be found in the constructor of CouchDB()

                self.server_url = parsed_url._replace(
                    netloc="{}:{}".format(parsed_url.hostname, parsed_url.port)).geturl()

here netloc is composed from parsed_url.hostname (without brackets) and the port number

the behaviour can easily be corrected by replacing with

               # is hostname a ipv6 address?
               if ':' in parsed_url.hostname:
                    # yes: apply brackets
                    self.server_url = parsed_url._replace(
                        netloc="[{}]:{}".format(parsed_url.hostname, parsed_url.port)).geturl()
                else:
                    self.server_url = parsed_url._replace(
                        netloc="{}:{}".format(parsed_url.hostname, parsed_url.port)).geturl()

**Comment by emlaver** [comment]
@ManfredEnning thanks for catching this! We'll add it to our backlog.  Would you be interested in opening a PR?

**Comment by ricellis** [comment]
Closing; this library is now EOL.
IPv6 addresses work correctly in our replacement [cloudant-python-sdk](https://github.com/IBM/cloudant-python-sdk/).
