### ISSUE TITLE
Creating a Design Doc with partitioned = false still creates design doc with partitioned enabled

### ISSUE THREAD

**Issue by CodipherX** [cloudant/python-cloudant#466]
Please [read these guidelines](http://ibm.biz/cdt-issue-guide) before opening an issue.

## Bug Description
I created a design document with following params:
ddoc = DesignDocument(db,"doc_id",partitioned=False)
However cloudant still created design doc with partitioned enabled in CouchDB

### 1. Steps to reproduce and the simplest code sample possible to demonstrate the issue

Create a design doc with following conf:
ddoc = DesignDocument(db,"doc_id",partitioned=False)
ddoc.add_view(ddoc_name,mapper)
ddoc.save()

### 2. What you expected to happen
The design doc should get created with partition disabled

### 3. What actually happened
The design doc gets created with partition enabled

## Environment details
Cloudant Version: 2.13.0
CouchDB: 3.0.0

## 4. Workaround
I found the possible cause of the issue in src/cloudant/design_document.py
In the init function, the setdefault is given only for partitioned=True. I added the options for else condition as well
if partitioned:
self.setdefault('options', {'partitioned': True})
else:
self.setdefault('options', {'partitioned': False})

it solved my issue.

**Comment by emlaver** [comment]
Hi @CodipherX, I'm not witnessing this issue when I try to create a design document in either a non-partitioned or a partitioned database.  
I also tried creating the design doc with and without the `partitioned=False` parameter and the response was what you'd expect to happen.
Environment:
Python: 3.7
python-cloudant: 2.13.0
Tried on both CouchDB 3.0.0 and Cloudant

**Comment by CodipherX** [comment]
Hi @emlaver , I tried doing a dummy experiment again and got the same issue. The steps I followed are:
1. Create a **partitioned** database `foo` in CouchDB
2. Ran the following script:
```
from cloudant import couchdb
from cloudant.design_document import DesignDocument

with couchdb('admin', 'admin', url='http://localhost:5984') as couchClient:
    
    db = couchClient['foo']
    ddoc = DesignDocument(db,'view',partitioned=False)
    ddoc.add_view('myview','function(doc) { emit(doc.foo, doc.bar); }')
    ddoc.save()
```
3. Checked the design doc info in the couchDB and got the following:
```
{
  "_id": "_design/view",
  "_rev": "1-c091b1c6dc79f702f339189348a97b99",
  "views": {
    "myview": {
      "map": "function(doc) { emit(doc.foo, doc.bar); }"
    }
  }
}
```
The partition is coming as enabled as can be seen below:
![fauxton](https://user-images.githubusercontent.com/23528226/81227210-ad9bdd80-9009-11ea-8ca4-9600558ff365.PNG)

However when I add the else clause as described in Workaround, I get the following info:
```
{
  "_id": "_design/view",
  "_rev": "5-884789917bd23ac2046aaf71d82efad9",
  "options": {
    "partitioned": false
  },
  "views": {
    "myview": {
      "map": "function(doc) { emit(doc.foo, doc.bar); }"
    }
  }
}
```

and the partition button is disabled
![fauxton2](https://user-images.githubusercontent.com/23528226/81227753-8bef2600-900a-11ea-9b40-948a4cb933e7.PNG)

**Comment by emlaver** [comment]
@CodipherX I can confirm that I'm seeing this issue as well.  Would you like to open up a PR with your fix?

**Comment by CodipherX** [comment]
@emlaver Sure. I will open a PR soon.
Thanks
