### ISSUE TITLE
Support for configuring number of shards and replicas for a couch database

### ISSUE THREAD

**Issue by CodipherX** [cloudant/python-cloudant#472]
Please [read these guidelines](http://ibm.biz/cdt-issue-guide) before opening an issue.

## Feature Request
From the source code, I found that it is not possible to use the cloudant to configure the shards and replica count of a database.
https://docs.couchdb.org/en/stable/cluster/sharding.html

I would like something as `couch_client.create_database(db_name, shards=3, replica=2, partitioned=False)`

## Environment details

Cloudant: 2.13
Python: 3.7

**Comment by bessbd** [comment]
Hi @CodipherX ,

Thank you for this feature request!
For `python-cloudant`, the primary purpose is allowing developers to interact with IBM Cloudant databases.
For IBM Cloudant, setting shard count and replicas is not enabled: https://cloud.ibm.com/docs/Cloudant?topic=cloudant-how-is-data-stored-in-ibm-cloudant-#setting-shard-count

I recommend using [Endpoint access](https://python-cloudant.readthedocs.io/en/stable/getting_started.html#endpoint-access) if you want to control shard count and replicas.
Also, I suggest being careful adjusting those values (or not adjusting them at all) as it's easy to run into issues of fault tolerance and/or performance by setting incorrect numbers.

**Comment by CodipherX** [comment]
Hi @bessbd ,

As of now, I have been using the Endpoint access. But it would be good to have this flexibility as part of `create_database()` function.
Please see if your team can accommodate this in the next major release.
Regards

**Comment by ricellis** [comment]
Our new [cloudant-python-sdk](https://github.com/IBM/cloudant-python-sdk/)(beta) makes the `q` [parameter available](https://cloud.ibm.com/apidocs/cloudant?code=python#putdatabase).
