### ISSUE TITLE
use_index param in get_query_result and get_partitioned_query_result does not support list data

### ISSUE THREAD

**Issue by CodipherX** [cloudant/python-cloudant#473]
Please [read these guidelines](http://ibm.biz/cdt-issue-guide) before opening an issue.

## Bug Description
As per https://docs.couchdb.org/en/stable/api/database/find.html#db-find , `use_index` could be either as `"<design_document>"` or `["<design_document>", "<index_name>"]`
However on putting a `list `in the `use_index` param, exception is thrown
### 1. Steps to reproduce and the simplest code sample possible to demonstrate the issue

1. Non-partitioned DB
```
from cloudant import couchdb

with couchdb("admin", "admin", url="http://localhost:5984") as couchClient:
    selector = {'_id': {'$gt': 0}}
    db = couchClient["foo"]
    docs = db.get_query_result(selector,use_index=["ddoc","index"],raw_result=True)

```

2. Partitioned DB
```
from cloudant import couchdb

with couchdb("admin", "admin", url="http://localhost:5984") as couchClient:
    selector = {'_id': {'$gt': 0}}
    db = couchClient["bar"]
    docs = db.get_partitioned_query_result("pkey",selector,use_index=["index","ddoc"],raw_result=True)

```

### 2. What you expected to happen
The query should run successfully
### 3. What actually happened
Exception is thrown `CloudantArgumentError: Argument use_index is not an instance of expected type: <class 'str'>`
## Environment details

Cloudant : 2.13
Python: 3.7

**Comment by bessbd** [comment]
Hi @CodipherX ,

The bug seems indeed valid: https://github.com/cloudant/python-cloudant/blob/14646b7c38caeceface6e2a35f94392356886b9f/src/cloudant/_common_util.py#L123 defines `use_index` as `STRTYPE` instead of `(STRTYPE, list)`.

Are you interested in opening a PR for this?

**Comment by CodipherX** [comment]
Hi @bessbd ,
I will open a PR soon.

Thanks and regards

**Comment by ricellis** [comment]
Our new [cloudant-python-sdk](https://github.com/IBM/cloudant-python-sdk/)(beta) has the [array form of the API](https://cloud.ibm.com/apidocs/cloudant?code=python#postfind) allowing for both a design document or a design document and an index to be specified in `use_index`.
