### ISSUE TITLE
Some how I am getting a weakreference

### ISSUE THREAD

**Issue by Mradr** [cloudant/python-cloudant#495]
More of a general question. Looks like calling dict( object ) or { **object } still keeps weakreference or a reference back to the document object. I was wondering, what is the proper method to copy the data without it updating back to the document object so changes do not effect the original object?

**Comment by eiri** [comment]
In general using `deepcopy` from [copy lib](https://docs.python.org/3/library/copy.html) seems to be a way to dealing with collections that are mutable or contain mutable items.

For general python questions I'd suggest to use knowledge forums like https://stackoverflow.com, you'll get much more complete answers there, and reserve this repo's issues for technical queries specific to `python-cloudant` lib.
