### ISSUE TITLE
Cannot use `Cloudant(username, password, account=account)` as context manager

### ISSUE THREAD

**Issue by mikerhodes** [cloudant/python-cloudant#53]
The following code fails:

```python
# With context manager
with Cloudant(USERNAME, PASSWORD, account=ACCOUNT_NAME) as client:
    session = client.session()
    database = client[DATABASE_NAME]
    document = database[DOC_NAME]
    print "Got document from context manager: ", document
```

With the following exception:

```
Traceback (most recent call last):
  File "main.py", line 20, in <module>
    with Cloudant(USERNAME, PASSWORD, account=ACCOUNT_NAME) as client:
AttributeError: __exit__
```

Looks like the object returned by the `Cloudant` call doesn't have the required methods for a context manager?

**Comment by alfinkel** [comment]
The call should be `with cloudant(USERNAME, PASSWORD, account=ACCOUNT_NAME) as client:` where `cloudant` is lowercase.  See https://github.com/cloudant/python-cloudant/blob/master/src/cloudant/__init__.py#L25
