### ISSUE TITLE
pip install not working from Project Jupyter

### ISSUE THREAD

**Issue by alfinkel** [cloudant/python-cloudant#54]
Moving this to its own issue.

See:  https://github.com/cloudant/python-cloudant/issues/49#issuecomment-164939376

**Comment by alfinkel** [comment]
@vinomaster, it appears that the problem you are experiencing is related to the conda container not having the correct `nameserver`.  I tried your [link](https://try.jupyter.org/) and it appears that I cannot install anything via `pip` in that conda container.  So it is not just limited to this Cloudant library.  I was, however, able to `pip install --pre cloudant` just fine in my own installation of Jupyter Notebooks which does not run out of a conda container but directly off of Python 2.7.  Are you locked in to using conda for your Python 2 kernel?  If so, then it may be possible to configure conda to recognize the appropriate `nameserver` as is done in a [similar problem](http://stackoverflow.com/questions/28668180/cant-install-pip-packages-inside-a-docker-container-with-ubuntu) I found when using a docker container on SO.  Unfortunately, I do not have any more details beyond that.  If not, then I suggest perhaps a venv with Python 2.7 and your own ipython notebooks install and I think that would resolve your issue with install of this library in Project Jupyter.

**Comment by parente** [comment]
If we're talking try.jupyter.org specifically, keep in mind it allows **no** external network access. You can try what they have installed, but you can't pull in anything new from the internet at large. Otherwise, it'd become a target for hosting all manner of unsavory content.

**Comment by alfinkel** [comment]
Good point @parente.  At this point it is only clear that there is a networking issue w.r.t. installing the library.  If the problem is on try.jupyter.org then the networking issue is because of what @parente pointed out in https://github.com/cloudant/python-cloudant/issues/54#issuecomment-165258265 and clearly there is no resolution to that.  If the problem is happening in a separate environment with known external network access using conda for Python2 then the problem is likely that the conda container does not know the correct nameserver as was mentioned in https://github.com/cloudant/python-cloudant/issues/54#issuecomment-165125976.  In either case, my recommendation would be to set up your own venv with Python 2.7 and ipython notebooks and this should resolve the issue.

**Comment by vinomaster** [comment]
Ok tactical workaround - install on a separate python2 env.
Strategic -- when will python-cloudant be supported on Python3?

**Comment by alfinkel** [comment]
Python3 support is slated to be part of the first stable release 2.0.0.  No date is available but we are adding functionality often.  So it shouldn't be too far down the road.  You can track the effort with #23.
