### ISSUE TITLE
Consider one location for library version number

### ISSUE THREAD

**Issue by alfinkel** [cloudant/python-cloudant#63]
In order to reduce/remove the possibility of discrepancy between the `__version__` string found in the library and the version of the library pushed to PyPI, we should place the version number in one location.

Based upon what I've read, there are three ways that I recommend we do this.
1. Put the version in setup.py and then in `__init__.py` we check for the version number via the package's metadata. That is, we add something like this to `__init__.py` (this comes straight from SO without a license, so we can't use this code verbatim)

``` python
from pkg_resources import get_distribution, DistributionNotFound
import os.path

try:
    _dist = get_distribution('cloudant')
    # Normalize case for Windows systems
    dist_loc = os.path.normcase(_dist.location)
    here = os.path.normcase(__file__)
    if not here.startswith(os.path.join(dist_loc, 'cloudant')):
        # not installed, but there is another version that *is*
        raise DistributionNotFound
except DistributionNotFound:
    __version__ = 'Please install this project with setup.py'
else:
    __version__ = _dist.version
```
1. Create a VERSION file that looks like

```
2.0.0b1
```

and then read it in `__init__.py`
1. Create a _version.py file that provides the looks like

``` python
__version_info__ = (2, 0, '0b1')
__version__ = '.'.join(__version__info)
```

We could also consider adding 'description', 'license', etc. to _version.py. It could be hard-coded here, and read by setup.py during the build, yet `__init__.py` would also read the version/info/etc from _version.py without having to resort to the installed package info (which, I suppose, would only be useful if somebody is using this library from the repository without actually installing it in their environment).

**Comment by alfinkel** [comment]
Also handle this for the Sphinx documentation docs/conf.py.

Ref:  https://github.com/cloudant/python-cloudant/pull/33#discussion_r46047379

**Comment by ricellis** [comment]
Won't fix. FWIW we sort of solved this problem in our new [cloudant-python-sdk](https://github.com/IBM/cloudant-python-sdk/)(beta) by using bump2version.
