### ISSUE TITLE
Investigate possible performance issues with client context manager

### ISSUE THREAD

**Issue by alfinkel** [cloudant/python-cloudant#64]
See https://github.com/cloudant/python-cloudant/pull/15#discussion_r41141609

**Comment by alfinkel** [comment]
I'm not sure that this addresses the question from the PR15 discussion but I wanted to note this link to Requests Session objects that I found researching something else.  It mentions Sessions using connection pooling.

http://docs.python-requests.org/en/latest/user/advanced/#session-objects

**Comment by alfinkel** [comment]
SO - Is Session from Requests thread safe?:

http://stackoverflow.com/questions/18188044/is-the-session-object-from-pythons-requests-library-thread-safe

Connection pooling issue discussion in Requests package:  

https://github.com/kennethreitz/requests/issues/1871 - BTW, the recommendation here is one session per thread.

Thread-safety articles:

http://effbot.org/zone/thread-synchronization.htm
http://www.laurentluce.com/posts/python-threads-synchronization-locks-rlocks-semaphores-conditions-events-and-queues/

**Comment by ricellis** [comment]
This has never been reported as a real problem in the field so hopefully it's good.
