### ISSUE TITLE
Exception handling

### ISSUE THREAD

**Issue by alfinkel** [cloudant/python-cloudant#65]
We need to firm up exception handling throughout the library.  
- Exception handling throughout needs to be revisited.
- But specifically, I want to call out the way the library (generally) behaves when a user is used to connect to an account that they do not own.

**Comment by alfinkel** [comment]
To drive home the point also see #71.

**Comment by emlaver** [comment]
Sub issues will be created for improving exception handling:
- When a user is used to connect to an account that they do not own
- When key name is invalid during document update (#195)

**Comment by rhyshort** [comment]
@emlaver Should this now be closed?

**Comment by emlaver** [comment]
@rhyshort We will keep this issue open as we still have these items:
- Continue to add response.raise_for_status()
- Non-reponse related error should be handled using either CloudantException, CloudantArgumentError, or ResultException
- Use design from ResultExeption to improve CloudantException
- Review library and ensure that CloudantException and CloudantArgumentError are being used appropriately

**Comment by rhyshort** [comment]
ok cool.

**Comment by emlaver** [comment]
Moving design improvements for CloudantException to issue #259.
