### ISSUE TITLE
Revisit the need for copyright notice at the top of each .py file

### ISSUE THREAD

**Issue by alfinkel** [cloudant/python-cloudant#68]
It was mentioned during a PR review that having a copyright statement at the top of each .py file is not really "Pythonic".  We chose at the time to keep all of the copyright statements and revisit the topic at a later date, perhaps with legal counsel that is well versed in open source code.

See conversation starting here:  https://github.com/cloudant/python-cloudant/pull/13#issuecomment-144094704

**Comment by ricellis** [comment]
We should leave the copyright statements in.
