### ISSUE TITLE
error message for invalid key name on update could be more informative

### ISSUE THREAD

**Issue by ewann** [cloudant/python-cloudant#71]
I should know better, but I happened to let one of these slip through. A 500 error is a little more raw than I think desirable here:  

pip freeze informs:
cloudant==2.0.0a4

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "tests_couchdb.py", line 144, in test_br
    my_document.save()
  File "/usr/lib/python2.7/site-packages/cloudant/document.py", line 170, in save
    put_resp.raise_for_status()
  File "/usr/lib/python2.7/site-packages/requests/models.py", line 837, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http://127.0.0.1:5984/my_database/julia30

Example code:
from cloudant.account import CouchDB
client = CouchDB('admin', 'admin', url='http://127.0.0.1:5984')
client.connect()
my_database = client.create_database('my_database')
my_database = client['my_database']

data = {
    '_id': 'julia30', # Setting _id is optional
    'name': 'Julia',
    'age': 30,
    'pets': ['cat', 'dog', 'frog']
    }

# Create a document using the Database API
my_document = my_database.create_document(data)

from cloudant.document import Document

# First retrieve the document
my_document = my_database['julia30']

# Update the document content
# This can be done as you would any other dictionary
my_document['name'] = 'Jules'
my_document['age'] = 6

my_document['_iShouldKnowBetter'] = True

# You must save the document in order to update it on the database
my_document.save()

It looks like a solution to this might eventually be wired up via:
https://github.com/cloudant/python-cloudant/blob/master/src/cloudant/errors.py ?

I wasn't (quickly) able to determine if I might be able to help here.

**Comment by alfinkel** [comment]
Exception and error handling is definitely something we plan to address.  It is on the radar and will be tracked here #65.
