### ISSUE TITLE
401 not authorized error when trying to get information about a database

### ISSUE THREAD

**Issue by ashutoshh** [cloudant/python-cloudant#87]
I want to get the size consumed by a database and as there is no function in the library I tried getting this information as follows:

client = Cloudant(USERNAME, PASSWORD,url=cloudantURL)
client.connect()
r=requests.Session()
response=''

url='https://username.cloudant.com/tweetdb'
data={'password':'########'}
response=r.post(url=url,data=data)
print response
client.disconnect()
This is throwing 401 error. Do I need to implement it using curl in python or is there any function in the library for fetching information of a database?

**Comment by rhyshort** [comment]
I think Database#metadata method is what your are looking for.

**Comment by ashutoshh** [comment]
yes... that is what i wanted... Thank you :)

**Comment by rhyshort** [comment]
Great, Your welcome :)
