### ISSUE TITLE
Expand on development standards in CONTRIBUTING.rst

### ISSUE THREAD

**Issue by alfinkel** [cloudant/python-cloudant#88]
We need to expand on coding standards, use of pylint, adding/running tests and so on for developers/contributors of this library.

**Comment by evansde77** [comment]
Just my 2p: Set up a default pylint configuration that matches your standards and a pep8 run using travis to run it.

**Comment by alfinkel** [comment]
@evansde77 - We have the pylint piece in place right now and travis runs it against the code base as part of the automated tests.  Does running a pep8 equivalent add any value?  I assume that it does.

**Comment by evansde77** [comment]
There is some overlap between pep8 and pylint, but it isnt 100%, pep8 is purely style, pylint has some style stuff but is mostly handy for errors, so I would run both.
