### ISSUE TITLE
Change view(ddoc,view, keys=[key1,key2]) to use JSON data for keys instead of encoding in URL

### ISSUE THREAD

**Issue by bradwbonn** [cloudant/python-cloudant#90]
Right now, the number of keys you can get from a view in the library is limited by the maximum length of the URL, which is woefully small.  Can this be changed to execute a GET or POST with -d {keys: [key1,key2...]} ?

**Comment by alfinkel** [comment]
Sure this makes sense.  We need to add logic [here](https://github.com/cloudant/python-cloudant/blob/master/src/cloudant/views.py#L246) to check for the existence of a "keys" parameter.  If one exists then execute the request as a POST otherwise exercise the request as a GET.

**Comment by bradwbonn** [comment]
Should probably also make sure all other methods pass the JSON data instead of append keys in the URL.  Such as database.all_docs()

**Comment by alfinkel** [comment]
Good point - we'll need to add the same logic [here](https://github.com/cloudant/python-cloudant/blob/master/src/cloudant/database.py#L379) as is described [above](https://github.com/cloudant/python-cloudant/issues/90#issuecomment-173986454) and also check the the entire library code base for these sort of GET calls to ensure that this is covered throughout.  I don't think that there are many/any other instances of this but I could be wrong.
