### ISSUE TITLE
CloudantDatabase doesn't allow for configuring fetch_limit

### ISSUE THREAD

**Issue by JanekLehr** [cloudant/python-cloudant#92]
[CloudantDatabase](https://github.com/cloudant/python-cloudant/blob/master/src/cloudant/database.py#L693) takes in `fetch_limit` as a parameter but will set the value to 100 regardless of what the class is instantiated with due to [this line](https://github.com/cloudant/python-cloudant/blob/master/src/cloudant/database.py#L697)

**Comment by alfinkel** [comment]
This has actually been fixed as part of #91 (https://github.com/cloudant/python-cloudant/pull/91/files#diff-0f234779ef2fcc77f8efea4570248fd4R698).  I just need to get it merged.

**Comment by JanekLehr** [comment]
:+1:
