### ISSUE TITLE
create_replication target

### ISSUE THREAD

**Issue by jlstack** [cloudant/python-cloudant#95]
I have ran into multiple issues while using create_replication. When passing create_replication two couchDB objects, the requests consistently failed. I noticed that the target url was formatted differently than the web UI. create_replication called "database_url" on the database object and it was formatted like so:

user:password@user.cloudant.com/my_sample_db

while the web UI formatted the url without the pre-appended user:password@:

user.cloudant.com/my_sample_db

I resolved the issue by passing in my own object with the url formatted like the web UI. Is there any reason as to why this would have made a difference?

**Comment by alfinkel** [comment]
The only way possible for your "database_url" to contain `user:password` as part of the url is if you defined that as your `url` kwarg when constructing your CouchDB client object.  This will cause issues and I am guessing that is what you are seeing.  If you haven't already done so, take a look at http://python-cloudant.readthedocs.org/en/latest/getting_started.html#connecting-with-a-client to see the proper way to connect to a CouchDB client using the url kwarg (The CouchDB part is commented out but it should still be clear).  If this does not solve your issue then can you provide a code sample of what is not working for you and we'll take a look and get you on the right track.

**Comment by jlstack** [comment]
You were correct. The url was being passed into the cloudant client constructor with the user:password pre-appended. This made it's way into the database_url as a result. Thank you for your help.
